---
title: "Select Models based on Cross-Validation and Apply to FY19"
author: "Yao"
date: "July 3-5, 2018"
output: html_document
---

Updated on 7/17/2018 to visualize the APE tables

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE,message=FALSE)
library(tidyverse)

# fast data format
library(feather)
library(reshape2)
```

```{r load data, echo=FALSE}
# Test on the selected region: FY19W07-FY19W20
APEresults <- read_feather("~/Yao_Rdata/APE_values.feather")

# Cross-validation on different quarters
APEresults_CV <- read_feather('~/Yao_Rdata/APE_values_CV.feather')

# Prepare the MAPE CV data table as reference
MAPE_CV.Table <- APEresults_CV %>% group_by(CFG,Region) %>% 
  summarise(Prophet=mean(APE_FcastRegion_Prophet,na.rm = TRUE),ARIMA=mean(APE_FcastRegion_ARIMA,na.rm = TRUE),TBATS=mean(APE_FcastRegion_TBATS,na.rm = TRUE),lm=mean(APE_FcastRegion_lm,na.rm = TRUE),RF=mean(APE_FcastRegion_RF,na.rm = TRUE),Xgboost=mean(APE_FcastRegion_Xgboost,na.rm = TRUE),Ensemble=mean(APE_FcastRegion_Ensemble,na.rm = TRUE))

```

The following part is based on mean MAPE over four quarters.

```{r Model Selection and Weighted, echo=FALSE}
MAPE_CV.Table$Selection <- apply(MAPE_CV.Table,1,function(x) names(which.min(x[3:9])))

APEresults %>% left_join(select(MAPE_CV.Table,CFG,Region,Selection)) -> APEresults.wtSelection
```

```{r Update errors for training Preferred Model, echo=FALSE}
# update each CFG and Region
UpdateOneRow <- function(OneRow){
  if (is.null(unlist(OneRow$Selection))){
    return(NA)
  }
  if (OneRow$Selection == "TBATS"){
    OneRow$Preferred <- OneRow$TBATS
  } else if (OneRow$Selection == "Xgboost") {
    OneRow$Preferred <- OneRow$Xgboost
  } else if (OneRow$Selection == "ARIMA") {
    OneRow$Preferred <- OneRow$ARIMA
  } else if (OneRow$Selection == "Prophet") {
    OneRow$Preferred <- OneRow$Prophet
  } else if (OneRow$Selection == "RF") {
    OneRow$Preferred <- OneRow$RF
  } else if (OneRow$Selection == "lm") {
    OneRow$Preferred <- OneRow$lm
  } else if (OneRow$Selection == "Ensemble") {
    OneRow$Preferred <- OneRow$Ensemble
  }
  return(OneRow$Preferred)
}

PreferredErrors <- apply(MAPE_CV.Table,1,UpdateOneRow)
MAPE_CV.Table$Preferred <- PreferredErrors # APE_FcastRegion_Preferred

MAPE_CV.Table[c("Selection" )] <- lapply(MAPE_CV.Table[c("Selection" )], function(x) as.factor(as.character(x)))

path <- "~/Yao_Rdata/MAPE_CV.wtSelection.feather"
write_feather(MAPE_CV.Table, path)

# Attainment Rates
Attainment_Rate_Cal <- function(x) {
  length(which(x<=20))/sum(!is.na(x))*100
}

# Consider weights
CFG_RGN_QTR_data.grouped <- read_feather("~/Yao_Rdata/CFG_RGN_Qtr_grouped.feather")
# Add a columne w: weight # The sum of w is 1.#
Total_Avg_Qtr_HDD_QTY <- sum(CFG_RGN_QTR_data.grouped$Avg_Qtr_HDD_QTY)
CFG_RGN_QTR_data.grouped$w <- CFG_RGN_QTR_data.grouped$Avg_Qtr_HDD_QTY/Total_Avg_Qtr_HDD_QTY
MAPE_CV.Table %>% left_join(CFG_RGN_QTR_data.grouped, by = c("CFG","Region"="RGN_DESC")) -> MAPE_CV.Table.weighted

write_excel_csv(MAPE_CV.Table.weighted,"~/Yao_Rdata/MAPE_CV.wtSelection.csv")

temp <- table(MAPE_CV.Table.weighted$Selection) %>% data.frame()

results.clean <- MAPE_CV.Table.weighted # consider all CFGs

Eval.results <- list()
# For different Regions
Region.groups <- unique(results.clean$Region)
len_Region <- length(Region.groups)
indx <- c('Prophet','ARIMA','TBATS','lm','RF','Xgboost','Ensemble','Preferred')
for (i_Region in 1:len_Region){
  data.selected <- filter(results.clean,Region==Region.groups[i_Region])
  AttainmentRates <- lapply(data.selected[indx],Attainment_Rate_Cal)
  # MAPE
  MAPE <- lapply(data.selected[indx],mean, na.rm = TRUE)
  MAPE_median <- lapply(data.selected[indx],median, na.rm = TRUE)
  # Weighted MAPE
  weighted_MAPE <- lapply(data.selected[indx],function(x) sum(x*data.selected$w,na.rm = TRUE))
  # combine
  Eval.results <- rbind(Eval.results,AttainmentRates,MAPE,MAPE_median,weighted_MAPE)
}

Eval.results_fcastRegion <- data.frame(Eval.results)
Eval.results_fcastRegion <- data.frame(Eval.results_fcastRegion,Region=rep(Region.groups,each = 3),Results=c('Attainment_Rates','MAPE','MAPE_median'))
Eval.results_fcastRegion[,1:8] <- lapply(Eval.results_fcastRegion[,1:8], function(x) as.numeric(as.character(x)))

write_feather(Eval.results_fcastRegion,"~/Yao_Rdata/Eval.CV_fcastRegion.feather")
```

```{r Update errors for testing Preferred Model, echo=FALSE}
# update each CFG and Region
UpdateOneRow <- function(OneRow){
  if (is.null(unlist(OneRow$Selection))){
    return(c(OneRow$MAPE_wk_Preferred,OneRow$APE_FcastRegion_Preferred))
  }
  if (OneRow$Selection == "TBATS"){
    OneRow$MAPE_wk_Preferred <- OneRow$MAPE_wk_TBATS
    OneRow$APE_FcastRegion_Preferred <- OneRow$APE_FcastRegion_TBATS
  } else if (OneRow$Selection == "Xgboost") {
    OneRow$MAPE_wk_Preferred <- OneRow$MAPE_wk_Xgboost
    OneRow$APE_FcastRegion_Preferred <- OneRow$APE_FcastRegion_Xgboost
  } else if (OneRow$Selection == "ARIMA") {
    OneRow$MAPE_wk_Preferred <- OneRow$MAPE_wk_ARIMA
    OneRow$APE_FcastRegion_Preferred <- OneRow$APE_FcastRegion_ARIMA
  } else if (OneRow$Selection == "Prophet") {
    OneRow$MAPE_wk_Preferred <- OneRow$MAPE_wk_Prophet
    OneRow$APE_FcastRegion_Preferred <- OneRow$APE_FcastRegion_Prophet
  } else if (OneRow$Selection == "RF") {
    OneRow$MAPE_wk_Preferred <- OneRow$MAPE_wk_RF
    OneRow$APE_FcastRegion_Preferred <- OneRow$APE_FcastRegion_RF
  } else if (OneRow$Selection == "lm") {
    OneRow$MAPE_wk_Preferred <- OneRow$MAPE_wk_lm
    OneRow$APE_FcastRegion_Preferred <- OneRow$APE_FcastRegion_lm
  } else if (OneRow$Selection == "Ensemble") {
    OneRow$MAPE_wk_Preferred <- OneRow$MAPE_wk_Ensemble
    OneRow$APE_FcastRegion_Preferred <- OneRow$APE_FcastRegion_Ensemble
  }
  return(c(OneRow$MAPE_wk_Preferred,OneRow$APE_FcastRegion_Preferred))
}

PreferredErrors <- apply(APEresults.wtSelection,1,UpdateOneRow) %>% t() %>% data.frame()
APEresults.wtSelection$MAPE_wk_Preferred <- PreferredErrors$X1 # MAPE_wk_Preferred
APEresults.wtSelection$APE_FcastRegion_Preferred <- PreferredErrors$X2 # APE_FcastRegion_Preferred

APEresults.wtSelection[c("Selection" )] <- lapply(APEresults.wtSelection[c("Selection" )], function(x) as.character(x))

path <- "~/Yao_Rdata/APEresults.wtSelection.feather"
write_feather(APEresults.wtSelection, path)

# Attainment Rates
Attainment_Rate_Cal <- function(x) {
  length(which(x<=20))/sum(!is.na(x))*100
}

results.clean <- APEresults.wtSelection # consider all CFGs

Eval.results <- list()
# For different Regions
Region.groups <- unique(results.clean$Region)
len_Region <- length(Region.groups)
indx <- c('MAPE_wk_MRP','APE_FcastRegion_MRP','MAPE_wk_Prophet','APE_FcastRegion_Prophet','MAPE_wk_ARIMA','APE_FcastRegion_ARIMA','MAPE_wk_TBATS','APE_FcastRegion_TBATS','MAPE_wk_lm','APE_FcastRegion_lm','MAPE_wk_RF','APE_FcastRegion_RF','MAPE_wk_Xgboost','APE_FcastRegion_Xgboost','MAPE_wk_Ensemble','APE_FcastRegion_Ensemble','MAPE_wk_Preferred','APE_FcastRegion_Preferred')
for (i_Region in 1:len_Region){
  data.selected <- filter(results.clean,Region==Region.groups[i_Region])
  AttainmentRates <- lapply(data.selected[indx],Attainment_Rate_Cal)
  # MAPE
  MAPE <- lapply(data.selected[indx],mean, na.rm = TRUE)
  MAPE_median <- lapply(data.selected[indx],median, na.rm = TRUE)
  # combine
  Eval.results <- rbind(Eval.results,AttainmentRates,MAPE,MAPE_median)
}

Eval.results_fcastRegion <- data.frame(Eval.results[,seq(2,18,2)])
dimnames(Eval.results_fcastRegion)[[2]] <- c('MRP','Prophet','ARIMA','TBATS','lm','RF','Xgboost','Ensemble','Preferred')
Eval.results_fcastRegion <- data.frame(Eval.results_fcastRegion,Region=rep(Region.groups,each = 3),Results=c('Attainment_Rates','MAPE','MAPE_median'))
Eval.results_fcastRegion[,1:9] <- lapply(Eval.results_fcastRegion[,1:9], function(x) as.numeric(as.character(x)))

Eval.results_wk <- data.frame(Eval.results[,seq(1,18,2)])
dimnames(Eval.results_wk)[[2]] <- c('MRP','Prophet','ARIMA','TBATS','lm','RF','Xgboost','Ensemble','Preferred')
Eval.results_wk <- data.frame(Eval.results_wk,Region=rep(Region.groups,each = 3),Results=c('Attainment_Rates','MAPE','MAPE_median'))
Eval.results_wk[,1:9] <- lapply(Eval.results_wk[,1:9], function(x) as.numeric(as.character(x)))

write_feather(Eval.results_fcastRegion,"~/Yao_Rdata/Eval.results_fcastRegion.feather")
write_feather(Eval.results_wk,"~/Yao_Rdata/Eval.results_wk.feather")
```

For different quarters, calculations are as follows.

```{r Model Selection and Weighted, echo=FALSE}
APEresults_CV <- data.frame(APEresults_CV[,c(1,2,3,seq(4,17,2))])
colnames(APEresults_CV) <- c("CFG","Region",'Quarter','Prophet','ARIMA','TBATS','lm','RF','Xgboost','Ensemble')
APEresults_CV$Selection <- apply(APEresults_CV,1,function(x) names(which.min(x[4:10])))
```

```{r Update errors for training Preferred Model, echo=FALSE}
# update each CFG and Region
UpdateOneRow <- function(OneRow){
  if (is.null(unlist(OneRow$Selection))){
    return(NA)
  }
  if (OneRow$Selection == "TBATS"){
    OneRow$Preferred <- OneRow$TBATS
  } else if (OneRow$Selection == "Xgboost") {
    OneRow$Preferred <- OneRow$Xgboost
  } else if (OneRow$Selection == "ARIMA") {
    OneRow$Preferred <- OneRow$ARIMA
  } else if (OneRow$Selection == "Prophet") {
    OneRow$Preferred <- OneRow$Prophet
  } else if (OneRow$Selection == "RF") {
    OneRow$Preferred <- OneRow$RF
  } else if (OneRow$Selection == "lm") {
    OneRow$Preferred <- OneRow$lm
  } else if (OneRow$Selection == "Ensemble") {
    OneRow$Preferred <- OneRow$Ensemble
  }
  return(OneRow$Preferred)
}

PreferredErrors <- apply(APEresults_CV,1,UpdateOneRow)
APEresults_CV$Preferred <- PreferredErrors # APE_FcastRegion_Preferred

APEresults_CV[c("Selection" )] <- lapply(APEresults_CV[c("Selection" )], function(x) as.factor(as.character(x)))

path <- "~/Yao_Rdata/MAPE_CV.wtSelection4Qtr.feather"
write_feather(APEresults_CV, path)

# Compare to the Test Region Selection
select(APEresults_CV,CFG,Region) %>% left_join(TestSelection) %>% unique() -> temp
write_excel_csv(temp,'temp.csv')

# Consider weights
HDD_data <- read_feather("~/Yao_Rdata/HDD_QTY_IRIS.feather")

CFG_RGN_Qtr_data <- HDD_data %>% 
  filter(Fiscal_Qtr %in% c('FY18Q1','FY18Q2','FY18Q3','FY18Q4')) %>%
  group_by(CFG,RGN_DESC,Fiscal_Qtr) %>%
  summarise(CFG_RGN_Qtr_QTY=sum(PART_QTY))

CFG_RGN_Qtr_data %>% ungroup() %>%
  group_by(CFG,RGN_DESC) %>%
  mutate(HDD_Volume_Group = case_when(
    CFG_RGN_Qtr_QTY <= 100 ~ 'Small',
    CFG_RGN_Qtr_QTY > 100 & CFG_RGN_Qtr_QTY <= 1000 ~ 'Medium',
    CFG_RGN_Qtr_QTY > 1000 & CFG_RGN_Qtr_QTY <= 10000 ~ 'Large',
    CFG_RGN_Qtr_QTY > 10000 ~ 'Strategic'
  )) -> CFG_RGN_Qtr_data.grouped

# Add a columne w: weight # The sum of w is 1.#
Total_CFG_RGN_Qtr_QTY <- sum(CFG_RGN_Qtr_data.grouped$CFG_RGN_Qtr_QTY)
CFG_RGN_Qtr_data.grouped$w <- CFG_RGN_Qtr_data.grouped$CFG_RGN_Qtr_QTY/Total_CFG_RGN_Qtr_QTY
APEresults_CV %>% left_join(CFG_RGN_Qtr_data.grouped, by = c("CFG","Region"="RGN_DESC","Quarter"="Fiscal_Qtr")) -> APEresults_CV.weighted

write_excel_csv(APEresults_CV.weighted,"~/Yao_Rdata/MAPE_CV.wtSelection.4Qtr.csv")

temp <- table(APEresults_CV.weighted$Selection) %>% data.frame()

# BY Region
p <- select(APEresults_CV.weighted,CFG,Region,Quarter,Selection) %>%
  filter(Selection != 'NULL') %>%
  ggplot(aes(x=Quarter,fill=Selection)) +
  geom_bar(position = "dodge") +
  labs(title = paste('Summary of Preferred Model'), x = "Models", y = 'Number of CFGs') + 
  theme_minimal(base_size = 14) + 
  scale_fill_tableau('tableau10medium') +
  facet_wrap(~Region, scales = "free", ncol = 1)
ggplotly(p)

# Overall Summary
data.selected <- select(APEresults_CV.weighted,CFG,Region,Quarter,Selection) %>% 
  filter(Selection != 'NULL') 
data.selected %>%
  dcast(Quarter~Selection, fun.aggregate = length) %>%
  melt(id.vars = "Quarter", measure.vars = c(levels(factor(data.selected$Selection)))) %>%
  ggplot(aes(x = Quarter,y = value, fill = variable)) + 
  geom_bar(stat = "identity", position = position_dodge(width = .8), width = 0.7) +
  geom_text(aes(label = value), position = position_dodge(width = .8), vjust = -0.5) +
  labs(title = paste('Summary of Preferred Model'), x = "Models", y = 'Number of CFGs') + 
  theme_minimal(base_size = 14) + 
  scale_fill_tableau('tableau10medium')


select(APEresults_CV.weighted,CFG,Region,Quarter,Selection) %>%
  spread(Quarter,Selection) -> PreferenceTable
write_excel_csv(PreferenceTable,"~/Yao_Rdata/MAPE_CV.wtSelection.4Qtr.v2.csv")
```
