---
title: "IRIS HDD Data Exploratory Analytics: CFG Clusters"
author: "Yao"
date: "June 20, 2018"
output: html_document
---

Latest update: 7/10/2018

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(scales)
library(ggthemes)
library(plotly)
library(reshape2)
library(imputeTS)
library(feather)
options(scipen = 999)
```

```{r load the IRIS HDD Sales Data}
hdd_qty <- read_feather("~/Yao_Rdata/HDD_QTY_IRIS.feather")

# join the CFG attribute table
# CFG information
CFG.info <- read.csv("~/Yao_Excels/CFGnamesInfo_filled.csv")
hdd_qty %>% left_join(CFG.info) -> data.joined
```


```{r By Region}
# Extract Quarterly Sales for each CFG
data.joined %>% 
  group_by(CFG,Fiscal_Qtr,RGN_DESC) %>%
  summarise(HDD_QTY=sum(PART_QTY)) -> temp_qtr

p <- temp_qtr %>% ggplot(aes(x=Fiscal_Qtr,y=HDD_QTY,group = CFG, color = RGN_DESC)) +
  geom_point(size = 2) +
  geom_line(size = 1.5,alpha=0.6) +
  labs(title = 'HDD Quarterly Sales by Region', x = "Fiscal Quarter", y = "Part Quantity") +
  theme_minimal(base_size = 14) +
  scale_color_tableau('tableau10medium') +
  scale_x_discrete(breaks = c('FY17Q1', 'FY18Q1', 'FY19Q1')) +
  scale_y_continuous(label=comma) + expand_limits(y = 0) +
  facet_wrap(~RGN_DESC,ncol = 3, scales = "fixed")
ggplotly(p)
```



