---
title: "IRIS HDD Data Exploratory Analytics: CFG Clusters"
author: "Yao"
date: "June 18, 2018"
output: html_document
---

Latest update: 6/19/2018

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(scales)
library(ggthemes)
library(plotly)
options(scipen = 999)
```

```{r load the IRIS HDD Sales Data}
load("~/Yao_Rdata/HDD_QTY_IRIS.RData")

# rm(list=setdiff(ls(),"hdd_qty"))
```

```{r CFG level exploration, echo=TRUE}
# Quarterly Sales for each CFG
hdd_qty %>% 
  group_by(CFG,Fiscal_Qtr) %>%
  summarise(CFG_Fiscal_Qtr_QTY=sum(PART_QTY)) -> temp_qtr

temp_qtr$CFG <- as.factor(temp_qtr$CFG)

temp_CFG <- temp_qtr %>% spread(Fiscal_Qtr,CFG_Fiscal_Qtr_QTY) %>% t() # CFG names kept

HDD.data <- temp_CFG %>% tail(n=nrow(temp_CFG)-1) %>% data.frame() # Only HDD data, col:CFG, row:qtr

HDD.data.numeric <- lapply(HDD.data,function(x) as.numeric(as.character(x))) %>% data.frame()

HDD.data.scaled <- HDD.data.numeric %>% scale() %>% data.frame() # scaled

HDD.scaled <- rbind(temp_CFG[1,],HDD.data.scaled) %>% t() %>% data.frame()

dimnames(HDD.scaled)[[2]] <- c('CFG',temp_qtr$Fiscal_Qtr[1:10])

HDD.scaled.plot <- HDD.scaled %>% gather(key="Fiscal_Qtr",value="CFG_Fiscal_Qtr_QTY",FY17Q1:FY19Q2)

AllCFG_Qtr.scaled <- HDD.scaled.plot %>% 
  ggplot(aes(x=Fiscal_Qtr,y=CFG_Fiscal_Qtr_QTY,group=CFG,color=CFG)) +
  geom_point(size = 2) +
  geom_line(size = 1.5) +
  labs(title = paste('HDD Quarterly Sales'), x = "Fiscal Quarter", y = "Part Quantity") + 
  theme_minimal(base_size = 12) + 
  #scale_color_tableau('tableau10medium') + 
  theme(legend.position = 'bottom',plot.title = element_text(hjust = 0.5))
# ggplotly(AllCFG_Qtr.scaled) 
# http://localhost:15618/session/viewhtml26488f61a3d/index.html # scaled by Quarter
# http://localhost:15618/session/viewhtml26484637683c/index.html # scaled by CFG
```

```{r kmeans cluster}
HDD.scaled %>% na.omit() -> HDD.clean
HDD.clean.numeric <- HDD.clean %>% select(starts_with("FY")) %>% lapply(function(x) as.numeric(as.character(x))) %>% data.frame() 
HDD.clean.numeric %>% kmeans(centers=4, nstart=10) -> km

HDD_clustered <- data.frame(CFG=HDD.clean$CFG,HDD.clean.numeric, CFGcluster=factor(km$cluster)) %>% gather(key="Fiscal_Qtr",value="CFG_Fiscal_Qtr_QTY",FY17Q1:FY19Q2)

AllCFG_Qtr.clusted <- HDD_clustered %>% filter(Fiscal_Qtr<'FY19Q2') %>%
  ggplot(aes(x=Fiscal_Qtr,y=CFG_Fiscal_Qtr_QTY,group=CFG,color=CFGcluster)) +
  geom_point(size = 2) +
  geom_line(size = 1.5) +
  labs(title = paste('HDD Quarterly Sales'), x = "Fiscal Quarter", y = "Part Quantity") + 
  theme_minimal(base_size = 11) + 
  scale_x_discrete(breaks = c('FY17Q1', 'FY18Q1', 'FY19Q1')) +
  theme(legend.position = 'bottom',plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(label=comma) + expand_limits(y = 0) +
  facet_wrap(~CFGcluster)
ggplotly(AllCFG_Qtr.clusted)
```

```{r Dertermine k value}
#
wss <- (nrow(HDD.clean.numeric)-1)*sum(apply(HDD.clean.numeric, 2, var))
# now calculate the weighted sum squares for all cluster numbers from 2 to 15
for (i in 2:15) wss[i] <- sum(kmeans(HDD.clean.numeric,
                                       nstart=10,
                                       centers=i)$withinss)
# turn wss data into a data frame for plotting
wss_data <- data.frame(centers=1:15, wss)
# make plot
ggplot(wss_data, aes(x=centers, y=wss)) + geom_point() + geom_line() +
  xlab("Number of Clusters") + ylab("Within groups sum of squares")
```

```{r Plot the clustered raw data}
temp_CFG <- temp_qtr %>% spread(Fiscal_Qtr,CFG_Fiscal_Qtr_QTY) %>% t() # CFG names kept

HDD.data <- temp_CFG %>% tail(n=nrow(temp_CFG)-1) %>% data.frame() # Only HDD data, col:CFG, row:qtr

HDD.data.numeric <- lapply(HDD.data,function(x) as.numeric(as.character(x))) %>% data.frame()

HDD.data.scaled <- HDD.data.numeric # no scaled

HDD.scaled <- rbind(temp_CFG[1,],HDD.data.scaled) %>% t() %>% data.frame()

dimnames(HDD.scaled)[[2]] <- c('CFG',temp_qtr$Fiscal_Qtr[1:10])

HDD.scaled %>% na.omit() -> HDD.clean
HDD.clean.numeric <- HDD.clean %>% select(starts_with("FY")) %>% lapply(function(x) as.numeric(as.character(x))) %>% data.frame() 

HDD_clustered <- data.frame(CFG=HDD.clean$CFG,HDD.clean.numeric, CFGcluster=factor(km$cluster)) %>% gather(key="Fiscal_Qtr",value="CFG_Fiscal_Qtr_QTY",FY17Q1:FY19Q2)

AllCFG_Qtr.raw <- HDD_clustered %>% filter(Fiscal_Qtr<'FY19Q2') %>%
  ggplot(aes(x=Fiscal_Qtr,y=CFG_Fiscal_Qtr_QTY,group=CFG,color=CFGcluster)) +
  geom_point(size = 2) +
  geom_line(size = 1.5) +
  labs(title = paste('HDD Quarterly Sales'), x = "Fiscal Quarter", y = "Part Quantity") + 
  theme_minimal(base_size = 11) + 
  scale_x_discrete(breaks = c('FY17Q1', 'FY18Q1', 'FY19Q1')) +
  theme(legend.position = 'bottom',plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(label=comma) + expand_limits(y = 0) +
  facet_wrap(~CFGcluster)
ggplotly(AllCFG_Qtr.raw)

```

I want to check the attributes of different clusters and see what findings I would have.
```{r}
# join the CFG attribute table

# CFG information
CFG.info <- read.csv("~/Yao_Excels/CFGnamesInfo.csv")

HDD_clustered %>% select(CFG,CFGcluster) %>% unique() %>% left_join(CFG.info) -> CFG.cluster.joined

# Interface
CFG.cluster.joined %>% select(CFGcluster,Interface) %>% 
  dcast(CFGcluster~Interface, fun.aggregate = length) %>%
  melt(id.vars = "CFGcluster", measure.vars = c(levels(factor(CFG.cluster.joined$Interface)),'NA')) %>%
  ggplot(aes(x = CFGcluster,y = value, fill = variable)) + 
  geom_bar(stat = "identity", position = position_dodge(width = .8), width = 0.7) +
  geom_text(aes(label = value), position = position_dodge(width = .8), vjust = -0.5) +
  labs(title = 'Interface Comparison of Different CFG Clusters', x = "CFG Clusters", y = "Interface",fill="Interface") + 
  theme_minimal(base_size = 14)

# Interface Speed
CFG.cluster.joined %>% select(CFGcluster,Interface_Speed) %>% 
  dcast(CFGcluster~Interface_Speed, fun.aggregate = length) %>%
  melt(id.vars = "CFGcluster", measure.vars = c(levels(factor(CFG.cluster.joined$Interface_Speed)),'NA')) %>%
  ggplot(aes(x = CFGcluster,y = value, fill = variable)) + 
  geom_bar(stat = "identity", position = position_dodge(width = .8), width = 0.7) +
  geom_text(aes(label = value), position = position_dodge(width = .8), vjust = -0.5) +
  labs(title = 'Interface Speed Comparison of Different CFG Clusters', x = "CFG Clusters", y = "Count", fill='Interface Speed') + 
  theme_minimal(base_size = 14) + 
  scale_fill_tableau('tableau10medium')

# Interface All
CFG.cluster.joined %>% select(CFGcluster,Interface_All) %>% 
  dcast(CFGcluster~Interface_All, fun.aggregate = length) %>%
  melt(id.vars = "CFGcluster", measure.vars = c(levels(factor(CFG.cluster.joined$Interface_All)),'NA')) %>%
  ggplot(aes(x = CFGcluster,y = value, fill = variable)) + 
  geom_bar(stat = "identity", position = position_dodge(width = .8), width = 0.7) +
  geom_text(aes(label = value), position = position_dodge(width = .8), vjust = -0.5) +
  labs(title = 'Interface All Comparison of Different CFG Clusters', x = "CFG Clusters", y = "Count", fill='Interface All') + 
  theme_minimal(base_size = 14) + 
  scale_fill_tableau('tableau10medium')

# Capacity
CFG.cluster.joined %>% select(CFGcluster,Capacity) %>% 
  dcast(CFGcluster~Capacity, fun.aggregate = length) %>%
  melt(id.vars = "CFGcluster", measure.vars = levels(factor(CFG.cluster.joined$Capacity))) %>%
  ggplot(aes(x = CFGcluster,y = value, fill = variable)) + 
  geom_bar(stat = "identity", position = position_dodge(width = .8), width = 0.7) +
  geom_text(aes(label = value), position = position_dodge(width = .8), vjust = -0.5) +
  labs(title = 'Capacity Comparison of Different CFG Clusters', x = "CFG Clusters", y = "Count", fill='Capacity') + 
  theme_minimal(base_size = 14)

# RPM
CFG.cluster.joined %>% select(CFGcluster,RPM) %>% 
  dcast(CFGcluster~RPM, fun.aggregate = length) %>%
  melt(id.vars = "CFGcluster", measure.vars = c(levels(factor(CFG.cluster.joined$RPM)),'NA')) %>%
  ggplot(aes(x = CFGcluster,y = value, fill = variable)) + 
  geom_bar(stat = "identity", position = position_dodge(width = .8), width = 0.7) +
  geom_text(aes(label = value), position = position_dodge(width = .8), vjust = -0.5) +
  labs(title = 'RPM Comparison of Different CFG Clusters', x = "CFG Clusters", y = "Count", fill='RPM') + 
  theme_minimal(base_size = 14) + 
  scale_fill_tableau('tableau10medium')

# Form Factor
CFG.cluster.joined %>% select(CFGcluster,Form_Factor) %>% 
  dcast(CFGcluster~Form_Factor, fun.aggregate = length) %>%
  melt(id.vars = "CFGcluster", measure.vars = c(levels(factor(CFG.cluster.joined$Form_Factor)),'NA')) %>%
  ggplot(aes(x = CFGcluster,y = value, fill = variable)) + 
  geom_bar(stat = "identity", position = position_dodge(width = .8), width = 0.7) +
  geom_text(aes(label = value), position = position_dodge(width = .8), vjust = -0.5) +
  labs(title = 'Form Factor Comparison of Different CFG Clusters', x = "CFG Clusters", y = "Count", fill='Form Factor') + 
  theme_minimal(base_size = 14) + 
  scale_fill_tableau('tableau10medium')
```

Will it be helpful if I add attributes to cluster CFGs?
```{r}

```



