---
title: "HDDFcastBaseline"
author: "Yao"
date: "June 8, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggthemes)
options(scipen = 999)
library(lubridate)
library(tidyquant)

library(scales) # for percent
```

## Use MRP to establish forecast accuracy baseline

```{r load the data}
Fcast_MRP <- read.csv('HDD_FY19_MRP.csv')

load("HDD_QTY_IRIS.RData")
hdd_qty$CFG <- as.factor(hdd_qty$CFG)
```

```{r Match CFG names}
# remove '_CFG' for MRP
Fcast_MRP$CFG = substr(Fcast_MRP$CFG,1,nchar(as.character(Fcast_MRP$CFG))-4)

# Weekly data from IRIS data
hdd_qty %>% group_by(CFG, Fiscal_Wk) %>%
  summarise(HDD_QTY = sum(PART_QTY)) -> HDD_Weekly

# Weekly data from MRP
Fcast_MRP %>% group_by(CFG, Fiscal_Wk) %>%
  summarise(HDD_Fcast = sum(value)) -> HDD_Weekly_MRP

# join
HDD_Weekly %>% full_join(HDD_Weekly_MRP) -> CFG_fcast.joined


```

```{r Visualize HDD_QTY and Forecast MRP}
CFGgroups <- levels(factor(CFG_fcast.joined$CFG))
len <- length(CFGgroups)

results <- data.frame() # save the error calculation results
for (i in 1:len){
  # HDD Weekly Sales
  temp_data <- filter(CFG_fcast.joined,CFG==CFGgroups[i]) # for certain CFG
  
  temp_data$HDD_Fcast[temp_data$HDD_Fcast == 0] <- NA # 0 means no forecast
  
  temp_data <- temp_data %>%
    mutate(.resid = HDD_QTY - HDD_Fcast)  %>%
    mutate(pct_err = .resid/HDD_QTY * 100, ape = abs(pct_err)) # calculate absolute percent error
  
  NonNAindex <- which(!is.na(temp_data$ape))
  firstNonNA <- min(NonNAindex,nrow(temp_data))
  lastNonNA <- max(NonNAindex,0)

  # Weekly Error Calculation
  mape_fcastPeriod_values <- mean(temp_data$ape[firstNonNA:lastNonNA])
  
  # 9-week Error Calculation
  MAPE_fcastPeriod <- abs(sum(temp_data$HDD_Fcast[firstNonNA:lastNonNA])-sum(temp_data$HDD_QTY[firstNonNA:lastNonNA]))/sum(temp_data$HDD_QTY[firstNonNA:lastNonNA]) * 100
  
  print(paste(CFGgroups[i],mape_fcastPeriod_values,MAPE_fcastPeriod,'week:',temp_data$Fiscal_Wk[firstNonNA],temp_data$Fiscal_Wk[lastNonNA]))
  
  results <- rbind(results,c(mape_fcastPeriod_values,MAPE_fcastPeriod))
  
  if (!is.na(MAPE_fcastPeriod)){
    p_week<- temp_data %>%
      ggplot(aes(x=Fiscal_Wk,y=HDD_QTY,group = 1)) +
      geom_point(size = 2, color = 'blue') +
      geom_line(aes(x=Fiscal_Wk,y=HDD_QTY),size = 1.5, color = 'blue') +
      geom_point(aes(x=Fiscal_Wk,y=HDD_Fcast),size = 2, color = 'orange') +
      geom_line(aes(x=Fiscal_Wk,y=HDD_Fcast),size = 1.5, color = 'orange',group = 1) +
      labs(title = paste(CFGgroups[i],'HDD Weekly Sales'), x = "Fiscal Week", y = "Part Quantity") + 
      theme_minimal(base_size = 14) + 
      scale_color_tableau('tableau10medium') + 
      scale_x_discrete(breaks = c('FY17W01', 'FY18W01', 'FY19W01')) +
      #theme(legend.position = 'none',plot.title = element_text(hjust = 0.5)) +
      scale_y_continuous(label=comma) + expand_limits(y = 0)
    ggsave(filename = paste(CFGgroups[i],'HDD Weekly Sales',".png"), p_week, width=10)
  }
}

dimnames(results)[[2]] <- c('MAPE_weekly','MAPE_FcastRegion')

num_CFG_valid <- nrow(na.omit(results)) # The total number of CFGs were forecasted.

Attainment_week <- nrow(results %>% filter(MAPE_weekly<=25))
Attainment_FcastRegion <- nrow(results %>% filter(MAPE_FcastRegion<=25))

Attainment_weekRate = Attainment_week/num_CFG_valid
print(percent(Attainment_weekRate))

Attainment_FcastRegionRate = Attainment_FcastRegion/num_CFG_valid
print(percent(Attainment_FcastRegionRate))

MAPE <- lapply(na.omit(results),mean, na.rm = TRUE)
MAPE_median <- lapply(na.omit(results),median, na.rm = TRUE)
print(MAPE)
print(MAPE_median)
```

