---
title: "Forecast_Function_Cinkie"
author: "Yao"
date: "August 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r forecast_functions}

calculate_attain = function(y, yhat){
  
  ## attain = actual / forecast
  if (yhat != 0){
    attain = y/yhat
  }else if (y == 0 & yhat == 0){
    attain = 1
  }else if ( y != 0 & yhat == 0){
    attain = 0
  }
  
  return(attain)
}

calculate_attain_flag = function(attain){
  
  ## attain = actual / forecast
  if (attain >= 0.8 & attain <= 1.2){
    attain_flag = "Green"
  }else if (attain > 1.2){
    attain_flag = "Red"
  }else if (attain < 0.8){
    attain_flag = "Blue"
  }else{
    attain_flag = NA
  }
  
  return(attain_flag)
}

calculate_ape = function(y, yhat){
  
  ape = ifelse(y == 0 & yhat == 0, 0, abs(y-yhat)/y)
  
  return(ifelse(is.infinite(ape), NA, ape))
}


mean_one = function(data_part_train, data_part_test, one_item, data_cadence, n_wk = 13){
  
  data_part_train_one = data_part_train %>% filter(CFG_New == one_item)
  data_part_test_one = data_part_test %>% filter(CFG_New == one_item)
  
  if (data_cadence == "Weekly"){
    
    latest_n_wkly_mean = data_part_train_one %>% 
      top_n(n_wk, ds) %>% 
      summarise(wk_mean = mean(y))
    
  }else if (data_cadence == "Daily"){
    
    latest_n_wkly_mean = data_part_train_one %>% 
      top_n(n_wk * 7, ds) %>% 
      summarise(wk_mean = sum(y) / n_wk)
    
  }
  
  result_tmp = data_part_test_one %>% 
    group_by(CFG_New) %>% 
    summarise(y = sum(y), yhat = latest_n_wkly_mean$wk_mean * 13) %>% 
    mutate(attain = calculate_attain(y, yhat),
           attain_flag = calculate_attain_flag(attain),
           ape = calculate_ape(y,yhat)) %>% 
    ungroup()
  
  return(result_tmp)
}

arima_one =function(data_part_train, data_part_test, one_item){
  
  data_part_train_one = data_part_train %>% filter(CFG_New == one_item)
  data_part_test_one = data_part_test %>% filter(CFG_New == one_item)
  
  train_ts = with(data_part_train_one %>% select(-CFG_New), zoo(y, order.by = ds))
  
  m_arima = auto.arima(train_ts)
  
  m_fcst = forecast(m_arima, h = 26)
  
  
  result_tmp = data_part_test_one %>% 
    group_by(CFG_New) %>% 
    summarise(y = sum(y), yhat = sum(m_fcst$mean[14:26])) %>% 
    mutate(attain = calculate_attain(y, yhat),
           attain_flag = calculate_attain_flag(attain),
           ape = calculate_ape(y,yhat)) %>%  
    ungroup()
  
  return(result_tmp)
}

ets_one =function(data_part_train, data_part_test, one_item){
  
  data_part_train_one = data_part_train %>% filter(CFG_New == one_item) %>% ungroup()
  data_part_test_one = data_part_test %>% filter(CFG_New == one_item) %>% ungroup()
  
  train_ts = with(data_part_train_one %>% select(-CFG_New), zoo(y, order.by = ds))
  
  m_ets = ets(train_ts)
  
  m_fcst = forecast(m_ets, h = 26)
  
  result_tmp = data_part_test_one %>% 
    group_by(CFG_New) %>% 
    summarise(y = sum(y), yhat = sum(m_fcst$mean[14:26])) %>% 
    mutate(attain = calculate_attain(y, yhat),
           attain_flag = calculate_attain_flag(attain),
           ape = calculate_ape(y,yhat)) %>% 
    ungroup()
  
  return(result_tmp)
}

bass_one =function(data_part_train, data_part_test, one_item){
  
  data_part_train_one = data_part_train %>% filter(CFG_New == one_item) %>% ungroup()
  data_part_test_one = data_part_test %>% filter(CFG_New == one_item) %>% ungroup()
  
  train_ts = as.ts(data_part_train_one$y)
  
  tryCatch({
    m_bass = diffusion(train_ts, cumulative = F)
    
    m_fcst = predict(m_bass, h = 26)
    
  }, error = function(e){print(paste("No Bass curve for", one_item))})
  
  if (exists("m_fcst")){
    result_tmp = data_part_test_one %>% 
      group_by(CFG_New) %>% 
      summarise(y = sum(y), yhat = sum(m_fcst$frc[14:26, "Adoption"])) %>% 
      mutate(attain = calculate_attain(y, yhat),
             attain_flag = calculate_attain_flag(attain),
             ape = calculate_ape(y,yhat)) %>% 
      ungroup()
  }else{
    result_tmp = data_part_test_one %>% 
      group_by(CFG_New) %>% 
      summarise(y = sum(y), yhat = NA, attain = NA, attain_flag = NA, ape = NA) %>% 
      ungroup()
  }
  
  return(result_tmp)
}

prophet_one = function(data_part_train, data_part_test, one_item){
  
  data_part_train_one = data_part_train %>% filter(CFG_New == one_item)
  data_part_test_one = data_part_test %>% filter(CFG_New == one_item)
  
  ## train and forecast
  prophet.fit = prophet(data_part_train_one, yearly.seasonality = TRUE, seasonality.mode = "multiplicative", weekly.seasonality = T)
  future = data.frame(ds = data_part_test_one$ds)
  forecast = predict(prophet.fit, future)
  
  result_tmp = data_part_test_one %>% 
    left_join(forecast %>% 
                mutate(ds = as.character(ds)), by = "ds") %>% 
    group_by(CFG_New) %>% 
    summarise(y = sum(y), yhat = sum(yhat)) %>% 
    mutate(attain = calculate_attain(y, yhat),
           attain_flag = calculate_attain_flag(attain),
           ape = calculate_ape(y,yhat)) %>% 
    ungroup()
  
  return(result_tmp)
}

xgboost_one = function(data_part_train, data_part_test, one_item){
  
  data_part_train_one = data_part_train %>% filter(CFG_New == one_item)
  data_part_test_one = data_part_test %>% filter(CFG_New == one_item)
  
  data_part_train_one = data_part_train_one %>% 
    select(-CFG_New) %>% 
    mutate(ds = as.Date(ds))
  
  timetk_train_data = data_part_train_one %>% 
    tk_augment_timeseries_signature() %>% 
    select(-c(ds, diff, month.lbl, wday.lbl))
  
  m1 = xgboost(data = as.matrix(select(timetk_train_data, -y)), label = timetk_train_data$y, nrounds = 20, verbose = 0)
  
  timetk_test_data = as.Date(data_part_test_one$ds) %>% 
    tk_get_timeseries_signature() %>% 
    select(-c(index, diff, month.lbl, wday.lbl))
  
  timetk_forecast = predict(m1, newdata = as.matrix(timetk_test_data))
  
  result_tmp = data_part_test_one %>% 
    group_by(CFG_New) %>% 
    summarise(y = sum(y), yhat = sum(timetk_forecast)) %>% 
    mutate(attain = calculate_attain(y, yhat),
           attain_flag = calculate_attain_flag(attain),
           ape = calculate_ape(y,yhat)) %>% 
    ungroup()
  
  return(result_tmp)
}


## forecst function , ahead is the month
forecast_cfg = function(data_part, test_qtrs, ahead = 3, data_cadence = c("Daily","Weekly"), cfg_ptg_threshold = 1, cfg_col = "CFG"){
  
  qtr_mo_tbl = data_part %>% 
    distinct(Calendar_Qtr, Fiscal_Mo) %>% 
    arrange(Fiscal_Mo)
  
  cmdy_list = sort(unique(data_part$ITM_TYPE))
  
  part_result = tibble(
    ITM_TYPE = character(0), CFG_New = character(0), test_qtr = character(0), model = character(0),
   y = numeric(0), yhat = numeric(0),
    attain = numeric(0), attain_flag = character(0), ape = numeric(0), num_cfg = numeric(0)
  )
  
  data_part = data_part %>% 
    rename_("CFG_New" = cfg_col)
  
  for (test_qtr in test_qtrs){
    
    # train end time (smaller than this train_end_qtr)
    train_end_mo = qtr_mo_tbl$Fiscal_Mo[min(which(qtr_mo_tbl$Calendar_Qtr == test_qtr)) - ahead]
    
    for (cmdy in cmdy_list){
      
      if (data_cadence == "Weekly"){
        
        data_part_tmp = data_part %>% 
          filter(ITM_TYPE == cmdy) %>% 
          group_by(Calendar_Qtr, Fiscal_Mo, Fiscal_Wk_End_Date, CFG_New) %>% 
          summarise(y = sum(ITM_QTY)) %>% 
          ungroup()
        
        data_part_tmp_train = data_part_tmp %>% 
          filter(Fiscal_Mo < train_end_mo) %>% 
          select(CFG_New, Fiscal_Wk_End_Date, y)
        
        data_part_tmp_test = data_part_tmp %>% 
          filter(Calendar_Qtr == test_qtr) %>% 
          select(CFG_New, Fiscal_Wk_End_Date, y)
        
        ## forecast the CFGs that exists in botn train and test set
        cfg_list_tmp = setdiff(intersect(unique(data_part_tmp_test$CFG_New), unique(data_part_tmp_train$CFG_New)), NA)
        
        ## not forecast CFGs with small volume, exclude CFGs based on their quantity contribution to cmdy total
        cfg_list_tbl_sm_vol = data_part_tmp_train %>% 
          group_by(CFG_New) %>% 
          summarise(y = sum(y)) %>% 
          arrange(desc(y)) %>% 
          mutate(cum_ptg = cumsum(y)/sum(y)) %>% 
          filter(cum_ptg > cfg_ptg_threshold)
        
        ## filter CFGs that have less than 3 historical data points
        cfg_list_tbl_no_data = data_part_tmp_train %>% 
          group_by(CFG_New) %>% 
          filter(y > 0) %>% 
          filter(Fiscal_Wk_End_Date == min(Fiscal_Wk_End_Date)) %>% 
          mutate(ds = ymd(Fiscal_Wk_End_Date),
                 rm_flag = (ds + weeks(3) >= max(data_part_tmp_train$Fiscal_Wk_End_Date))) %>% 
          filter(rm_flag)
        
        cfg_list_rm = unique(union(cfg_list_tbl_sm_vol$CFG_New, cfg_list_tbl_no_data$CFG_New))
        
        cfg_list_test = setdiff(cfg_list_tmp, cfg_list_rm)
        
        ## CFGs removed in test
        data_test_rm_vol = data_part_tmp_test %>%
          mutate(cfg_rm_flag = !(CFG_New %in% cfg_list_test)) %>% 
          group_by(cfg_rm_flag) %>% 
          summarise(rm_y = sum(y)) %>% 
          mutate(rm_ptg = rm_y / sum(rm_y)) %>% 
          filter(cfg_rm_flag)
        
        data_part_train = data_part_tmp_train %>% 
          filter(CFG_New %in% cfg_list_test) %>% 
          rename(ds = Fiscal_Wk_End_Date) %>% 
          arrange(CFG_New, ds)
        
        data_part_test = data_part_tmp_test %>% 
          filter(CFG_New %in% cfg_list_test) %>% 
          rename(ds = Fiscal_Wk_End_Date) %>% 
          arrange(CFG_New, ds)
        
      }else if (data_cadence == "Daily"){
        
        data_part_tmp = data_part %>% 
          filter(ITM_TYPE == cmdy) %>% 
          group_by(Calendar_Qtr, Fiscal_Mo, Fiscal_Wk, Fiscal_Date, CFG_New) %>% 
          summarise(y = sum(ITM_QTY)) %>% 
          ungroup()
        
        data_part_tmp_train = data_part_tmp %>% 
          filter(Fiscal_Mo < train_end_mo) %>% 
          select(CFG_New, Fiscal_Date, y)
        
        data_part_tmp_test = data_part_tmp %>% 
          filter(Calendar_Qtr == test_qtr) %>% 
          select(CFG_New, Fiscal_Date, y)
        
        ## forecast the CFGs that exists in botn train and test set
        cfg_list_tmp = setdiff(intersect(unique(data_part_tmp_test$CFG_New), unique(data_part_tmp_train$CFG_New)), NA)
        
        ## not forecast CFGs with small volume, exclude CFGs based on their quantity contribution to cmdy total
        cfg_list_tbl_sm_vol = data_part_tmp_train %>% 
          group_by(CFG_New) %>% 
          summarise(y = sum(y)) %>% 
          arrange(desc(y)) %>% 
          mutate(cum_ptg = cumsum(y)/sum(y)) %>% 
          filter(cum_ptg > cfg_ptg_threshold)
        
        ## filter CFGs that have less than 3 week historical data points
        cfg_list_tbl_no_data = data_part_tmp_train %>% 
          group_by(CFG_New) %>% 
          filter(y > 0) %>% 
          filter(Fiscal_Date == min(Fiscal_Date)) %>% 
          mutate(ds = ymd(Fiscal_Date),
                 rm_flag = (ds + weeks(3) >= max(data_part_tmp_train$Fiscal_Date))) %>% 
          filter(rm_flag)
        
        cfg_list_rm = unique(union(cfg_list_tbl_sm_vol$CFG_New, cfg_list_tbl_no_data$CFG_New))
        
        cfg_list_test = setdiff(cfg_list_tmp, cfg_list_rm)
        
        ## CFGs removed in test
        data_test_rm_vol = data_part_tmp_test %>%
          mutate(cfg_rm_flag = !(CFG_New %in% cfg_list_test)) %>% 
          group_by(cfg_rm_flag) %>% 
          summarise(rm_y = sum(y)) %>% 
          mutate(rm_ptg = rm_y / sum(rm_y)) %>% 
          filter(cfg_rm_flag)
        
        data_part_train = data_part_tmp_train %>% 
          filter(CFG_New %in% cfg_list_test) %>% 
          rename(ds = Fiscal_Date) %>% 
          arrange(CFG_New, ds)
        
        data_part_test = data_part_tmp_test %>% 
          filter(CFG_New %in% cfg_list_test) %>% 
          rename(ds = Fiscal_Date) %>% 
          arrange(CFG_New, ds)
      }
      # ---------------------------------------- Mean ---------------------------------------- #####
      
      result_mean = foreach(i = 1:length(cfg_list_test), .combine = rbind, 
                            .packages = c("dplyr"), 
                            .export = c("mean_one", "calculate_attain", "calculate_attain_flag", "calculate_ape")) %dopar% {
                              
                              mean_one(data_part_train, data_part_test, cfg_list_test[i], data_cadence, n_wk = 13)  } 
      result_mean$model = "Naive Mean"
      
      # ---------------------------------------- Arima ---------------------------------------- #####
      
      result_arima = foreach(i = 1:length(cfg_list_test), .combine = rbind, 
                             .packages = c("dplyr", "zoo", "forecast"), 
                             .export = c("arima_one", "calculate_attain", "calculate_attain_flag", "calculate_ape")) %dopar% {
                               
                               arima_one(data_part_train, data_part_test, cfg_list_test[i])  } 
      result_arima$model = "ARIMA"
      
      # ---------------------------------------- ETS ---------------------------------------- #####
      
      result_ets = foreach(i = 1:length(cfg_list_test), .combine = rbind, 
                           .packages = c("dplyr", "zoo", "forecast"), 
                           .export = c("ets_one", "calculate_attain", "calculate_attain_flag", "calculate_ape")) %dopar% {
                             
                             ets_one(data_part_train, data_part_test, cfg_list_test[i])  } 
      result_ets$model = "ETS"
      
      # ---------------------------------------- BASS Diffusion ---------------------------------------- #####
      
      result_bass = foreach(i = 1:length(cfg_list_test), .combine = rbind, 
                            .packages = c("dplyr", "diffusion", "zoo", "forecast"), 
                            .export = c("bass_one", "calculate_attain", "calculate_attain_flag", "calculate_ape")) %dopar% {
                              
                              bass_one(data_part_train, data_part_test, cfg_list_test[i])  } 
      result_bass$model = "Bass"
      
      # ---------------------------------------- XGBoost ---------------------------------------- #####
      result_xgboost = foreach(i = 1:length(cfg_list_test), .combine = rbind, 
                               .packages = c("dplyr", "xgboost", "timetk"), 
                               .export = c("xgboost_one", "calculate_attain", "calculate_attain_flag", "calculate_ape")) %dopar% {
                                 
                                 xgboost_one(data_part_train, data_part_test, cfg_list_test[i])  } 
      
      result_xgboost$model = "XGBoost"
      
      # # ---------------------------------------- Prophet ---------------------------------------- #####
      ##### Prophet's error rate is really, really high ######
      # result_prophet = foreach(i = 1:length(cfg_list_test), .combine = rbind,
      #                                 .packages = c("prophet","dplyr"), 
      # .export = c("prophet_one", "calculate_attain", , "calculate_attain_flag""calculate_ape")) %dopar% {
      # 
      #                                   prophet_one(data_part_train, data_part_test, cfg_list_test[i])  }
      # 
      # result_prophet$model = "Prophet"
      
      # ---------------------------------------- Aggregate results ---------------------------------------- #####
      result_tmp = bind_rows(result_mean, result_arima, result_ets, result_bass, result_xgboost)
      
      result_tmp$num_cfg = length(cfg_list_test)
      
      result_tmp = result_tmp %>% 
        mutate(ITM_TYPE = cmdy, test_qtr = test_qtr)
      
      if (nrow(data_test_rm_vol) == 0){
        
        result_tmp = result_tmp %>% 
          mutate(rm_y = 0, rm_y_ptg = 0)
        
      }else{
        
        result_tmp = result_tmp %>% 
          mutate(rm_y = data_test_rm_vol$rm_y,
                 rm_y_ptg = data_test_rm_vol$rm_ptg)
      }
      
      part_result = bind_rows(part_result, result_tmp)
      
      rm(result_tmp, data_part_tmp, data_part_tmp_train, data_part_tmp_test, data_test_rm_vol, result_tmp)
    }## end of ITM_TYPE loop
    
  }## end of test quarters loop
  
  return(part_result)
}
```