---
title: "HDD Forecast compared to MRP"
author: "Yao"
date: "Jul 30, 2018"
output: html_document
---

Updated on 07/30/2018.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(feather)
options(scipen = 999)
```

## Load Database from SQL Server

```{r ConnectDB}
library(DBI)
db = dbConnect(odbc::odbc(),
               driver = 'SQL Server',
               server = 'IRISAGL01.aus.amer.dell.com',
               user = 'Yao_Z',
               password = 'y67uhgt$Y')
```

Download the latest HDD sales data from SQL server.

```{sql hdd_qty, connection=db, output.var = 'hdd_qty'}
SELECT 
  D.Cfg_Desc AS CFG, D.sku_num, D.Sample_DPN, C.Fiscal_Qtr, C.Fiscal_Mo, C.Fiscal_Wk, C.Fiscal_Wk_End_Date, C.Fiscal_Date, C.Fiscal_Yr, B.Order_Date_week, C.Fiscal_Mo_End_Date,  C.Fiscal_Qtr_End_Date,
  CASE WHEN A.LOB_DESC = 'PowerEdge' AND A.ESI_order_flag = 'Y' THEN 'PowerEdge - ESI'
                     WHEN A.MGMT_PROD_LVL_3_NM = 'Storage' AND A.DELL_EMC_ORDER_FLAG = 'DELL' THEN 'Storage - DELL'
                ELSE A.LOB_DESC END AS LOB_DESC, A.BRAND_CATG_DESC, 
  A.RGN_DESC,
  A.GBL_PARNT_ACCT_NM AS Customer, 
  SUM(SYS_QTY_DELL) AS SYS_QTY,
  SUM(ITM_QTY) AS PART_QTY
FROM IRIS.[Base].[ISG_Business_Transformation.isgOrders] AS A 
JOIN IRIS.[Base].[ISG_Business_Transformation.isgOrdersDetails] B
ON A.ORD_NBR = B.ORD_NBR AND A.FMLY_PFOLIO_DESC = B.FMLY_PFOLIO_DESC AND A.SRC_BU_ID = B.SRC_BU_ID
JOIN IRIS.DIM.Date C
ON B.ORD_DT = C.Fiscal_Date
JOIN IRIS_Data_Mart.[dbo].[SKU_CFG_Bridge] D
ON B.ITM_NBR = D.sku_num
WHERE D.Cfg_Desc LIKE '%HDD%' AND Commodity_Desc IN ('Hard Drive', 'Controller Cards/HBA') AND A.DELL_EMC_ORDER_FLAG = 'DELL' AND (A.LOB_DESC IN ('PowerEdge','Cloud Products') OR A.MGMT_PROD_LVL_3_NM = 'Storage') ---AND C.Fiscal_Yr >= 'FY16'
GROUP BY
  D.Cfg_Desc, D.sku_num, D.Sample_DPN, C.Fiscal_Qtr, C.Fiscal_Mo, C.Fiscal_Wk, C.Fiscal_Wk_End_Date, C.Fiscal_Date, C.Fiscal_Yr, B.Order_Date_week, C.Fiscal_Mo_End_Date,  C.Fiscal_Qtr_End_Date,
  CASE WHEN A.LOB_DESC = 'PowerEdge' AND A.ESI_order_flag = 'Y' THEN 'PowerEdge - ESI'
                   WHEN A.MGMT_PROD_LVL_3_NM = 'Storage' AND A.DELL_EMC_ORDER_FLAG = 'DELL' THEN 'Storage - DELL'
                   ELSE A.LOB_DESC END, A.BRAND_CATG_DESC, 
  A.RGN_DESC, A.GBL_PARNT_ACCT_NM
ORDER BY D.Cfg_Desc, C.Fiscal_Qtr, C.Fiscal_Mo, C.Fiscal_Wk
```


```{r Deal with missing data}
Weekly_HDD_QTY_combined <- hdd_qty %>% group_by(Order_Date_week,Fiscal_Wk) %>% summarise(Fiscal_Wk_QTY=sum(PART_QTY))
# 7/20/2018 128 weeks

apply(hdd_qty, 2, function(x) any(is.na(x)))

# Columns have NA: Customer
hdd_qty = hdd_qty %>% 
  mutate(Customer = ifelse(
    grepl('Dummy|disti|\032|APPOINTED|ACCT-R', Customer, ignore.case = T) | Customer == '' | is.na(Customer),
    'Unknown_Customer', Customer
  ))

apply(hdd_qty, 2, function(x) any(is.na(x)))
# All NAs have been cleaned.

write_feather(hdd_qty,'~/Yao_Rdata/HDD_QTY_IRIS.feather')
```

Download the latest versions of MRP data.

```{sql connection=db, output.var = 'mrp_data0'}
SELECT [VERSION], MONWKYR, CFG, REGION, SUM(DATA) AS MRP_CT, Commodity_Desc
FROM IRIS.Base.MRP_Weekly A
JOIN IRIS.DIM.DPN B 
ON A.PART = B.DPN
WHERE B.CFG LIKE '%HDD%' AND B.Commodity_Desc IN ('Hard Drive')--Verified with other restrictions. Good for now.
GROUP BY [VERSION], MONWKYR, CFG, REGION, Commodity_Desc
```

```{r Save and read mrp_HDD data}
write_feather(mrp_data0,'~/Yao_Rdata/mrp_HDD.feather')

mrp_data0 <- read_feather('~/Yao_Rdata/mrp_HDD.feather')
```

The MONWKYR in MRP data are actually Calendar Month, Fiscal Week, and Fiscal Year.

```{r Use the Hyperion_Calendar_Mapping to map the MRP MONWKYR to Fiscal Calendar}
# Hyperion_Calendar_Mapping.xlsx
library(readxl)
Hyperion_Calendar_Mapping <- read_excel("~/Yao_Rdata/Hyperion_Calendar_Mapping.xlsx")
mrp_data0 %>% left_join(unique(select(Hyperion_Calendar_Mapping,-Fiscal_Date)),by=c('MONWKYR'='Hyperion_Wk_MONWKYR')) -> mrp_data.calr_mapped

write_feather(mrp_data.calr_mapped,'~/Yao_Rdata/mrp_HDD_caldr_mapped.feather')
```

Read the mapped mrp_data.

```{r Read the mapped mrp_data}
mrp_data <- read_feather('~/Yao_Rdata/mrp_HDD_caldr_mapped.feather')
```


