---
title: "HDD Forecast Results Evaluation by Region"
author: "Yao"
date: "June 8-29, 2018"
output: html_document
---

Updated on 07/23/2018
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE,message=FALSE)
library(tidyverse)
library(ggthemes)
options(scipen = 999)
library(lubridate)
library(tidyquant)
library(plotly)

library(scales) # for percent

# make the code parallel using 'parallel' package
library(iterators)
library(parallel)
library(foreach)
library(doParallel)

# Calculate the number of cores
no_cores <- detectCores() - 1
registerDoParallel(no_cores)

# fast data format
library(feather)
```

## My models compared to MRP

```{r load the data, eval=FALSE, include=FALSE}
# This chunk was run once, and then done.
# MRP
Fcast_MRP <- read.csv('~/Yao_Excels/HDD_FY19_MRP.csv') 
# remove '_CFG' for MRP
Fcast_MRP$CFG = as.factor(substr(Fcast_MRP$CFG,1,nchar(as.character(Fcast_MRP$CFG))-4))

# All mine
Fcast_Yao_Global <- read_feather('~/Yao_Rdata/All_fcast_Global.feather')
Fcast_Yao_Rgn <- read_feather('~/Yao_Rdata/All_fcast_Rgn.feather')
Fcast_Yao_Global$Region <- 'Global'
Fcast_Yao <- rbind(Fcast_Yao_Global,Fcast_Yao_Rgn)

# HDD data from IRIS
hdd_qty <- read_feather("~/Yao_Rdata/HDD_QTY_IRIS.feather")
hdd_qty$CFG <- as.factor(hdd_qty$CFG)
hdd_qty$Region <- as.factor(hdd_qty$RGN_DESC)

# Check the existing regions and make them match each other
# unique(hdd_qty$RGN_DESC)
# unique(Fcast_MRP$Region)
# unique(Fcast_Yao$Region)
Fcast_MRP.Americas <- filter(Fcast_MRP,Region=='AMF')
Fcast_MRP.Americas$Region <- as.factor('Americas')
Fcast_MRP <- rbind(Fcast_MRP.Americas,filter(Fcast_MRP,Region=='APJ'|Region=='EMEA'))
rm(Fcast_MRP.Americas,Fcast_Yao_Global,Fcast_Yao_Rgn)
```

```{r Match CFG names, eval=FALSE, include=FALSE}
# This chunk was run once, and then done.
# Weekly data from IRIS data
hdd_qty %>% group_by(CFG, Region, Fiscal_Wk) %>%
  summarise(HDD_QTY = sum(PART_QTY)) %>%
  gather(Model,HDD_QTY,HDD_QTY)-> HDD_Weekly_Rgn
hdd_qty %>% group_by(CFG, Fiscal_Wk) %>%
  summarise(HDD_QTY = sum(PART_QTY)) %>%
  gather(Model,HDD_QTY,HDD_QTY)-> HDD_Weekly_Global
HDD_Weekly_Global$Region <- 'Global'
HDD_Weekly <- rbind(HDD_Weekly_Global,HDD_Weekly_Rgn)
rm(HDD_Weekly_Global,HDD_Weekly_Rgn)

# Weekly data from MRP
Fcast_MRP %>% group_by(CFG, Region, Fiscal_Wk) %>%
  summarise(MRP_Fcast = sum(value)) %>%
  gather(Model,HDD_QTY,MRP_Fcast)-> HDD_Weekly_MRP_Rgn
Fcast_MRP %>% group_by(CFG, Fiscal_Wk) %>%
  summarise(MRP_Fcast = sum(value)) %>%
  gather(Model,HDD_QTY,MRP_Fcast)-> HDD_Weekly_MRP_Global
HDD_Weekly_MRP_Global$Region <- 'Global'
HDD_Weekly_MRP <- rbind(HDD_Weekly_MRP_Global,HDD_Weekly_MRP_Rgn)
rm(HDD_Weekly_MRP_Global,HDD_Weekly_MRP_Rgn)

# join
HDD_Weekly %>% full_join(HDD_Weekly_MRP) %>% 
  full_join(Fcast_Yao) -> CFG_fcast.joined
rm(HDD_Weekly,HDD_Weekly_MRP,hdd_qty,Fcast_MRP,Fcast_Yao)

write_feather(CFG_fcast.joined, "~/Yao_Rdata/CFG_fcast_joined.feather")
```

```{r Load feather data}
# Load feather data
CFG_fcast.joined <- read_feather("~/Yao_Rdata/CFG_fcast_joined.feather")
CFG_RGN_QTR_data.grouped <- read_feather("~/Yao_Rdata/CFG_RGN_Qtr_grouped.feather")
# Add a columne w: weight # The sum of w is 1.#
Total_Avg_Qtr_HDD_QTY <- sum(CFG_RGN_QTR_data.grouped$Avg_Qtr_HDD_QTY)
CFG_RGN_QTR_data.grouped$w <- CFG_RGN_QTR_data.grouped$Avg_Qtr_HDD_QTY/Total_Avg_Qtr_HDD_QTY
```

```{r Visualize HDD_QTY and Forecast MRP}
# Get all CFG names, all Region names, and all Model names
CFGgroups <- levels(factor(CFG_fcast.joined$CFG))
len_CFG <- length(CFGgroups)
Region.groups <- levels(factor(CFG_fcast.joined$Region))
len_Region <- length(Region.groups)
Model.groups <- levels(factor(CFG_fcast.joined$Model))

# less than 0 means no forecast
# CFG_fcast.joined$HDD_QTY[CFG_fcast.joined$HDD_QTY <= 0] <- NA

l_ggplotly <- htmltools::tagList()
# For each CFG
for (i_CFG in 1:len_CFG) {
  # For each Region
  for (i_Region in 1:len_Region){
    # HDD Weekly Sales for certain CFG and selected Region
    temp_data <- filter(CFG_fcast.joined,CFG==CFGgroups[i_CFG],Region==Region.groups[i_Region])
    
    if (nrow(temp_data)>0) {
      if (0){
        p_week<- temp_data %>%
          ggplot(aes(x=Fiscal_Wk,y=HDD_QTY,group = Model, color = Model)) +
          geom_point(size = 2) +
          geom_line(size = 1.5,alpha=0.6) +
          labs(title = paste(CFGgroups[i_CFG],Region.groups[i_Region],'HDD Weekly Sales'), x = "Fiscal Week", y = "Part Quantity") + 
          theme_minimal(base_size = 14) + 
          scale_color_tableau('tableau10medium') + 
          scale_x_discrete(breaks = c('FY17W01', 'FY18W01', 'FY19W01')) +
          scale_y_continuous(label=comma) + expand_limits(y = 0)
        l_ggplotly[[(i_CFG-1)*len_Region+i_Region]] <- ggplotly(p_week,width = 999)
        #ggsave(filename = paste(CFGgroups[i],' HDD Weekly Sales',".png",sep = ''), p_week, width=10)
      }
    }
  }
}
#l_ggplotly
```

```{r Calculate errors}
# Data transformation for error calculations
CFG_fcast.joined[!is.na(CFG_fcast.joined$Model),] %>% spread(Model,HDD_QTY) %>% ungroup() -> CFG_fcast

CFG_fcast$Ensemble <- rowMeans(select(CFG_fcast,ARIMA,Prophet,TBATS,timetk_RF,timetk_Xgboost), na.rm = TRUE) # removed timetk_lm

CFG_fcast %>% gather(Model,HDD_QTY,ARIMA:Ensemble) -> CFG_fcast.joined.2
write_feather(CFG_fcast.joined.2, "~/Yao_Rdata/CFG_fcast_joined.feather")

#CFG_cast <- read_feather("~/Yao_Rdata/CFG_fcast.feather")

# CFG_fcast.na.omitted <- na.omit(CFG_fcast) %>% # Excluded some CFGs that do not have all model results. I do not want this.
CFG_fcast <- filter(CFG_fcast,Fiscal_Wk>="FY19W07" & Fiscal_Wk<="FY19W22") %>%
  # For MAE: mean(abs(error)) # calculate abs(error) here
  mutate(err_MRP = abs(HDD_QTY - MRP_Fcast),err_Prophet = abs(HDD_QTY - Prophet),err_ARIMA = abs(HDD_QTY - ARIMA),err_TBATS = abs(HDD_QTY - TBATS),err_lm = abs(HDD_QTY - timetk_lm),err_RF = abs(HDD_QTY - timetk_RF),err_Xgboost = abs(HDD_QTY - timetk_Xgboost),err_Ensemble = abs(HDD_QTY - Ensemble)) %>%
  # calculate absolute percent error for all models
  mutate(ape_MRP = err_MRP/HDD_QTY * 100,ape_Prophet = err_Prophet/HDD_QTY * 100,ape_ARIMA = err_ARIMA/HDD_QTY * 100,ape_TBATS = err_TBATS/HDD_QTY * 100,ape_lm = err_lm/HDD_QTY * 100,ape_RF = err_RF/HDD_QTY * 100,ape_Xgboost = err_Xgboost/HDD_QTY * 100,ape_Ensemble = err_Ensemble/HDD_QTY * 100)
  ###### RMSE (root mean squared error), also called RMSD (root mean squared deviation), and MAE (mean absolute error) are both used to evaluate models by summarizing the differences between the actual (observed) and predicted values. MAE gives equal weight to all errors, while RMSE gives extra weight to large errors.
  # Calulate RMSE: sqrt(mean(error^2)) #

# Function that returns Root Mean Squared Error
RMSE <- function(error)
{
    sqrt(mean(error^2,na.rm = TRUE))
}


# Get all CFG names, all Region names, and all Model names
CFGgroups2 <- levels(factor(CFG_fcast$CFG))
len_CFG <- length(CFGgroups2)
Region.groups <- levels(factor(CFG_fcast$Region))
len_Region <- length(Region.groups)

results <- foreach(i_CFG=1:len_CFG, .combine=rbind, .packages=c('tidyverse')) %dopar% {
  # HDD Weekly Sales for certain CFG and selected Region
  # For each Region
  OneCFG <- list()
  for (i_Region in 1:len_Region){
    temp_data <- filter(CFG_fcast,CFG==CFGgroups2[i_CFG],Region==Region.groups[i_Region])
    print(paste(CFGgroups2[i_CFG],Region.groups[i_Region],'PASSED!'))
    totalHDD <- sum(temp_data$HDD_QTY)
    w <- temp_data$HDD_QTY/totalHDD
    
    # MRP
    # Metric 1: Weighted MAPE by Week / WAPE
    mape_wk_MRP <- weighted.mean(temp_data$ape_MRP,temp_data$HDD_QTY, na.rm = TRUE)
    # Metric 1.2: WAPE # Is this the same as my Weighted MAPE by Week? Yep!
    WAPE_MRP <- sum(temp_data$err_MRP, na.rm = TRUE)/totalHDD*100
    # Metric 1.3: Aggregated APE during the forecast period # The same as 1 and 1.2? Yes!
    APE_fcastPeriod_MRP <- abs(sum(temp_data$MRP_Fcast, na.rm = TRUE)-totalHDD)/totalHDD * 100
    
    # Metric 2: Aggregated Weighted APE
    Aggregated_weighted_APE_MRP <- sum(w*temp_data$err_MRP, na.rm = TRUE)/sum(w*temp_data$HDD_QTY, na.rm = TRUE)*100
    # Metric 3: MASE: Mean Absolute Scaled Error
    MASE_wk_MRP <- mean(abs(temp_data$err_MRP/temp_data$err_MRP), na.rm = TRUE)
    # Metric 4 Aggregated Absolute Scaled Error
    AASE_fcastPeriod_MRP <- abs(sum(temp_data$err_MRP, na.rm = TRUE)/sum(temp_data$err_MRP, na.rm = TRUE))
    # Metric 5: Mean RMSE by Week
    RMSE_wk_MRP <- RMSE(temp_data$err_MRP)
    # Metric 6: Aggregatred RMSE/MAE per week
    AAE_fcastPeriod_per_week_MRP <- abs(sum(temp_data$MRP_Fcast, na.rm = TRUE)-totalHDD)/nrow(temp_data)
    # Metric 6.2: MAE # The same as 6---No!
    MAE_wk_MRP <- mean(temp_data$err_MRP, na.rm = TRUE)
    
    MRP <- c(CFGgroups2[i_CFG],Region.groups[i_Region],'MRP',mape_wk_MRP,WAPE_MRP,APE_fcastPeriod_MRP,Aggregated_weighted_APE_MRP,MASE_wk_MRP,AASE_fcastPeriod_MRP,RMSE_wk_MRP,AAE_fcastPeriod_per_week_MRP,MAE_wk_MRP)
    
    # Prophet
    # Metric 1: Weighted MAPE by Week / WAPE
    mape_wk_Prophet <- weighted.mean(temp_data$ape_Prophet,temp_data$HDD_QTY, na.rm = TRUE)
    # Metric 1.2: WAPE # Is this the same as my Weighted MAPE by Week? Yep!
    WAPE_Prophet <- sum(temp_data$err_Prophet, na.rm = TRUE)/totalHDD*100
    # Metric 1.3: Aggregated APE during the forecast period # The same as 1 and 1.2? No, this cancelled out some errors, which is not good.
    APE_fcastPeriod_Prophet <- abs(sum(temp_data$Prophet, na.rm = TRUE)-totalHDD)/totalHDD * 100
    
    # Metric 2: Aggregated Weighted APE
    Aggregated_weighted_APE_Prophet <- sum(w*temp_data$err_Prophet, na.rm = TRUE)/sum(w*temp_data$HDD_QTY, na.rm = TRUE)*100
    # Metric 3: MASE: Mean Absolute Scaled Error
    MASE_wk_Prophet <- mean(abs(temp_data$err_Prophet/temp_data$err_MRP), na.rm = TRUE)
    # Metric 4 Aggregated Absolute Scaled Error
    AASE_fcastPeriod_Prophet <- abs(sum(temp_data$err_Prophet, na.rm = TRUE)/sum(temp_data$err_MRP, na.rm = TRUE))
    # Metric 5: Mean RMSE by Week
    RMSE_wk_Prophet <- RMSE(temp_data$err_Prophet)
    # Metric 6: Aggregatred RMSE/MAE per week
    AAE_fcastPeriod_per_week_Prophet <- abs(sum(temp_data$Prophet, na.rm = TRUE)-totalHDD)/nrow(temp_data)
    # Metric 6.2: MAE # The same as 6? No, the Metric 6 cancelled out some errors in different weeks.
    MAE_wk_Prophet <- mean(temp_data$err_Prophet, na.rm = TRUE)
    
    Prophet <- c(CFGgroups2[i_CFG],Region.groups[i_Region],'Prophet',mape_wk_Prophet,WAPE_Prophet,APE_fcastPeriod_Prophet,Aggregated_weighted_APE_Prophet,MASE_wk_Prophet,AASE_fcastPeriod_Prophet,RMSE_wk_Prophet,AAE_fcastPeriod_per_week_Prophet,MAE_wk_Prophet)
    
    # ARIMA
    # Weekly Error Calculation
    # Metric 1: Weighted MAPE by Week / WAPE
    mape_wk_ARIMA <- weighted.mean(temp_data$ape_ARIMA,temp_data$HDD_QTY, na.rm = TRUE)
    # Metric 1.2: WAPE # Is this the same as my Weighted MAPE by Week? Yep!
    WAPE_ARIMA <- sum(temp_data$err_ARIMA, na.rm = TRUE)/totalHDD*100
    # Metric 1.3: Aggregated APE during the forecast period # The same as 1 and 1.2? Yes!
    APE_fcastPeriod_ARIMA <- abs(sum(temp_data$ARIMA, na.rm = TRUE)-totalHDD)/totalHDD * 100
    
    # Metric 2: Aggregated Weighted APE
    Aggregated_weighted_APE_ARIMA <- sum(w*temp_data$err_ARIMA, na.rm = TRUE)/sum(w*temp_data$HDD_QTY, na.rm = TRUE)*100
    # Metric 3: MASE: Mean Absolute Scaled Error
    MASE_wk_ARIMA <- mean(abs(temp_data$err_ARIMA/temp_data$err_MRP), na.rm = TRUE)
    # Metric 4 Aggregated Absolute Scaled Error
    AASE_fcastPeriod_ARIMA <- abs(sum(temp_data$err_ARIMA, na.rm = TRUE)/sum(temp_data$err_MRP, na.rm = TRUE))
    # Metric 5: Mean RMSE by Week
    RMSE_wk_ARIMA <- RMSE(temp_data$err_ARIMA)
    # Metric 6: Aggregatred RMSE/MAE per week
    AAE_fcastPeriod_per_week_ARIMA <- abs(sum(temp_data$ARIMA, na.rm = TRUE)-totalHDD)/nrow(temp_data)
    # Metric 6.2: MAE # The same as 6
    MAE_wk_ARIMA <- mean(temp_data$err_ARIMA, na.rm = TRUE)
    
    ARIMA <- c(CFGgroups2[i_CFG],Region.groups[i_Region],'ARIMA',mape_wk_ARIMA,WAPE_ARIMA,APE_fcastPeriod_ARIMA,Aggregated_weighted_APE_ARIMA,MASE_wk_ARIMA,AASE_fcastPeriod_ARIMA,RMSE_wk_ARIMA,AAE_fcastPeriod_per_week_ARIMA,MAE_wk_ARIMA)
    
    # TBATS
    # Metric 1: Weighted MAPE by Week / WAPE
    mape_wk_TBATS <- weighted.mean(temp_data$ape_TBATS,temp_data$HDD_QTY, na.rm = TRUE)
    # Metric 1.2: WAPE # Is this the same as my Weighted MAPE by Week? Yep!
    WAPE_TBATS <- sum(temp_data$err_TBATS, na.rm = TRUE)/totalHDD*100
    # Metric 1.3: Aggregated APE during the forecast period # The same as 1 and 1.2? Yes!
    APE_fcastPeriod_TBATS <- abs(sum(temp_data$TBATS, na.rm = TRUE)-totalHDD)/totalHDD * 100
    
    # Metric 2: Aggregated Weighted APE
    Aggregated_weighted_APE_TBATS <- sum(w*temp_data$err_TBATS, na.rm = TRUE)/sum(w*temp_data$HDD_QTY, na.rm = TRUE)*100
    # Metric 3: MASE: Mean Absolute Scaled Error
    MASE_wk_TBATS <- mean(abs(temp_data$err_TBATS/temp_data$err_MRP), na.rm = TRUE)
    # Metric 4 Aggregated Absolute Scaled Error
    AASE_fcastPeriod_TBATS <- abs(sum(temp_data$err_TBATS, na.rm = TRUE)/sum(temp_data$err_MRP, na.rm = TRUE))
    # Metric 5: Mean RMSE by Week
    RMSE_wk_TBATS <- RMSE(temp_data$err_TBATS)
    # Metric 6: Aggregatred RMSE/MAE per week
    AAE_fcastPeriod_per_week_TBATS <- abs(sum(temp_data$TBATS, na.rm = TRUE)-totalHDD)/nrow(temp_data)
    # Metric 6.2: MAE # The same as 6
    MAE_wk_TBATS <- mean(temp_data$err_TBATS, na.rm = TRUE)
    
    TBATS <- c(CFGgroups2[i_CFG],Region.groups[i_Region],'TBATS',mape_wk_TBATS,WAPE_TBATS,APE_fcastPeriod_TBATS,Aggregated_weighted_APE_TBATS,MASE_wk_TBATS,AASE_fcastPeriod_TBATS,RMSE_wk_TBATS,AAE_fcastPeriod_per_week_TBATS,MAE_wk_TBATS)
    
    # timetk lm
    # Metric 1: Weighted MAPE by Week / WAPE
    mape_wk_lm <- weighted.mean(temp_data$ape_lm,temp_data$HDD_QTY, na.rm = TRUE)
    # Metric 1.2: WAPE # Is this the same as my Weighted MAPE by Week? Yep!
    WAPE_lm <- sum(temp_data$err_lm, na.rm = TRUE)/totalHDD*100
    # Metric 1.3: Aggregated APE during the forecast period # The same as 1 and 1.2? Yes!
    APE_fcastPeriod_lm <- abs(sum(temp_data$timetk_lm, na.rm = TRUE)-totalHDD)/totalHDD * 100
    
    # Metric 2: Aggregated Weighted APE
    Aggregated_weighted_APE_lm <- sum(w*temp_data$err_lm, na.rm = TRUE)/sum(w*temp_data$HDD_QTY, na.rm = TRUE)*100
    # Metric 3: MASE: Mean Absolute Scaled Error
    MASE_wk_lm <- mean(abs(temp_data$err_lm/temp_data$err_MRP), na.rm = TRUE)
    # Metric 4 Aggregated Absolute Scaled Error
    AASE_fcastPeriod_lm <- abs(sum(temp_data$err_lm, na.rm = TRUE)/sum(temp_data$err_MRP, na.rm = TRUE))
    # Metric 5: Mean RMSE by Week
    RMSE_wk_lm <- RMSE(temp_data$err_lm)
    # Metric 6: Aggregatred RMSE/MAE per week
    AAE_fcastPeriod_per_week_lm <- abs(sum(temp_data$timetk_lm, na.rm = TRUE)-totalHDD)/nrow(temp_data)
    # Metric 6.2: MAE # The same as 6
    MAE_wk_lm <- mean(temp_data$err_lm, na.rm = TRUE)
    
    lm <- c(CFGgroups2[i_CFG],Region.groups[i_Region],'LinearModel',mape_wk_lm,WAPE_lm,APE_fcastPeriod_lm,Aggregated_weighted_APE_lm,MASE_wk_lm,AASE_fcastPeriod_lm,RMSE_wk_lm,AAE_fcastPeriod_per_week_lm,MAE_wk_lm)
    
    # timetk RF
    # Metric 1: Weighted MAPE by Week / WAPE
    mape_wk_RF <- weighted.mean(temp_data$ape_RF,temp_data$HDD_QTY, na.rm = TRUE)
    # Metric 1.2: WAPE # Is this the same as my Weighted MAPE by Week? Yep!
    WAPE_RF <- sum(temp_data$err_RF, na.rm = TRUE)/totalHDD*100
    # Metric 1.3: Aggregated APE during the forecast period # The same as 1 and 1.2? Yes!
    APE_fcastPeriod_RF <- abs(sum(temp_data$timetk_RF, na.rm = TRUE)-totalHDD)/totalHDD * 100
    
    # Metric 2: Aggregated Weighted APE
    Aggregated_weighted_APE_RF <- sum(w*temp_data$err_RF, na.rm = TRUE)/sum(w*temp_data$HDD_QTY, na.rm = TRUE)*100
    # Metric 3: MASE: Mean Absolute Scaled Error
    MASE_wk_RF <- mean(abs(temp_data$err_RF/temp_data$err_MRP), na.rm = TRUE)
    # Metric 4 Aggregated Absolute Scaled Error
    AASE_fcastPeriod_RF <- abs(sum(temp_data$err_RF, na.rm = TRUE)/sum(temp_data$err_MRP, na.rm = TRUE))
    # Metric 5: Mean RMSE by Week
    RMSE_wk_RF <- RMSE(temp_data$err_RF)
    # Metric 6: Aggregatred RMSE/MAE per week
    AAE_fcastPeriod_per_week_RF <- abs(sum(temp_data$timetk_RF, na.rm = TRUE)-totalHDD)/nrow(temp_data)
    # Metric 6.2: MAE # The same as 6
    MAE_wk_RF <- mean(temp_data$err_RF, na.rm = TRUE)
    
    RF <- c(CFGgroups2[i_CFG],Region.groups[i_Region],'RandomForest',mape_wk_RF,WAPE_RF,APE_fcastPeriod_RF,Aggregated_weighted_APE_RF,MASE_wk_RF,AASE_fcastPeriod_RF,RMSE_wk_RF,AAE_fcastPeriod_per_week_RF,MAE_wk_RF)
    
    # timetk Xgboost
    # Metric 1: Weighted MAPE by Week / WAPE
    mape_wk_Xgboost <- weighted.mean(temp_data$ape_Xgboost,temp_data$HDD_QTY, na.rm = TRUE)
    # Metric 1.2: WAPE # Is this the same as my Weighted MAPE by Week? Yep!
    WAPE_Xgboost <- sum(temp_data$err_Xgboost, na.rm = TRUE)/totalHDD*100
    # Metric 1.3: Aggregated APE during the forecast period # The same as 1 and 1.2? Yes!
    APE_fcastPeriod_Xgboost <- abs(sum(temp_data$timetk_Xgboost, na.rm = TRUE)-totalHDD)/totalHDD * 100
    
    # Metric 2: Aggregated Weighted APE
    Aggregated_weighted_APE_Xgboost <- sum(w*temp_data$err_Xgboost, na.rm = TRUE)/sum(w*temp_data$HDD_QTY, na.rm = TRUE)*100
    # Metric 3: MASE: Mean Absolute Scaled Error
    MASE_wk_Xgboost <- mean(abs(temp_data$err_Xgboost/temp_data$err_MRP), na.rm = TRUE)
    # Metric 4 Aggregated Absolute Scaled Error
    AASE_fcastPeriod_Xgboost <- abs(sum(temp_data$err_Xgboost, na.rm = TRUE)/sum(temp_data$err_MRP, na.rm = TRUE))
    # Metric 5: Mean RMSE by Week
    RMSE_wk_Xgboost <- RMSE(temp_data$err_Xgboost)
    # Metric 6: Aggregatred RMSE/MAE per week
    AAE_fcastPeriod_per_week_Xgboost <- abs(sum(temp_data$timetk_Xgboost, na.rm = TRUE)-totalHDD)/nrow(temp_data)
    # Metric 6.2: MAE # The same as 6
    MAE_wk_Xgboost <- mean(temp_data$err_Xgboost, na.rm = TRUE)
    
    Xgboost <- c(CFGgroups2[i_CFG],Region.groups[i_Region],'Xgboost',mape_wk_Xgboost,WAPE_Xgboost,APE_fcastPeriod_Xgboost,Aggregated_weighted_APE_Xgboost,MASE_wk_Xgboost,AASE_fcastPeriod_Xgboost,RMSE_wk_Xgboost,AAE_fcastPeriod_per_week_Xgboost,MAE_wk_Xgboost)
    
    # Ensemble
    # Metric 1: Weighted MAPE by Week / WAPE
    mape_wk_Ensemble <- weighted.mean(temp_data$ape_Ensemble,temp_data$HDD_QTY, na.rm = TRUE)
    # Metric 1.2: WAPE # Is this the same as my Weighted MAPE by Week? Yep!
    WAPE_Ensemble <- sum(temp_data$err_Ensemble, na.rm = TRUE)/totalHDD*100
    # Metric 1.3: Aggregated APE during the forecast period # The same as 1 and 1.2? Yes!
    APE_fcastPeriod_Ensemble <- abs(sum(temp_data$Ensemble, na.rm = TRUE)-totalHDD)/totalHDD * 100
    
    # Metric 2: Aggregated Weighted APE
    Aggregated_weighted_APE_Ensemble <- sum(w*temp_data$err_Ensemble, na.rm = TRUE)/sum(w*temp_data$HDD_QTY, na.rm = TRUE)*100
    # Metric 3: MASE: Mean Absolute Scaled Error
    MASE_wk_Ensemble <- mean(abs(temp_data$err_Ensemble/temp_data$err_MRP), na.rm = TRUE)
    # Metric 4 Aggregated Absolute Scaled Error
    AASE_fcastPeriod_Ensemble <- abs(sum(temp_data$err_Ensemble, na.rm = TRUE)/sum(temp_data$err_MRP, na.rm = TRUE))
    # Metric 5: Mean RMSE by Week
    RMSE_wk_Ensemble <- RMSE(temp_data$err_Ensemble)
    # Metric 6: Aggregatred RMSE/MAE per week
    AAE_fcastPeriod_per_week_Ensemble <- abs(sum(temp_data$Ensemble, na.rm = TRUE)-totalHDD)/nrow(temp_data)
    # Metric 6.2: MAE # The same as 6
    MAE_wk_Ensemble <- mean(temp_data$err_Ensemble, na.rm = TRUE)
    
    Ensemble <- c(CFGgroups2[i_CFG],Region.groups[i_Region],'Ensemble',mape_wk_Ensemble,WAPE_Ensemble,APE_fcastPeriod_Ensemble,Aggregated_weighted_APE_Ensemble,MASE_wk_Ensemble,AASE_fcastPeriod_Ensemble,RMSE_wk_Ensemble,AAE_fcastPeriod_per_week_Ensemble,MAE_wk_Ensemble)
    
    OneRow <- rbind(MRP,Prophet,ARIMA,TBATS,lm,RF,Xgboost,Ensemble)
    OneCFG <- rbind(OneCFG,OneRow)
  }
  return(OneCFG)
}


dimnames(results)[[2]] <- c('CFG','Region','Model','MAPE_wk','WAPE','APE_fcastPeriod','Aggregated_weighted_APE','MASE_wk','AASE_fcastPeriod','RMSE_wk','AAE_fcastPeriod_per_week','MAE_wk')
results <- data.frame(results)
indx <- c('MAPE_wk','WAPE','APE_fcastPeriod','Aggregated_weighted_APE','MASE_wk','AASE_fcastPeriod','RMSE_wk','AAE_fcastPeriod_per_week','MAE_wk')
results[indx] <- lapply(results[indx], function(x) as.numeric(as.character(x)))
results[c("CFG","Region",'Model' )] <- lapply(results[c("CFG","Region",'Model' )], function(x) as.character(x))

results %>% left_join(CFG_RGN_QTR_data.grouped, by = c("CFG","Region"="RGN_DESC")) -> results.weight

path <- "~/Yao_Rdata/EvaluationResults.feather"
write_feather(results, path)
# 
# # Attainment Rates
# Attainment_Rate_Cal <- function(x) {
#   length(which(x<=20))/sum(!is.na(x))*100
# }
# 
# results.clean <- results.weight # consider all CFGs
# 
# Eval.results <- list()
# # For different Regions
# for (i_Region in 1:len_Region){
#   data.selected <- filter(results.clean,Region==Region.groups[i_Region])
#   AttainmentRates <- lapply(data.selected[indx],Attainment_Rate_Cal)
#   # MAPE
#   MAPE <- lapply(data.selected[indx],mean, na.rm = TRUE)
#   MAPE_median <- lapply(data.selected[indx],median, na.rm = TRUE)
#   # Weighted MAPE
#   Aggregated_weighted_APE <- lapply(data.selected[indx],function(x) sum(x*data.selected$w,na.rm = TRUE))
#   weighted_MAPE2 <- lapply(data.selected[indx],weighted.mean, data.selected$w, na.rm = TRUE)
#   # combine
#   Eval.results <- rbind(Eval.results,AttainmentRates,MAPE,MAPE_median,weighted_MAPE,weighted_MAPE2)
# }
# 
# Eval.results_fcastRegion <- data.frame(Eval.results[,seq(2,18,2)])
# dimnames(Eval.results_fcastRegion)[[2]] <- c('MRP','Prophet','ARIMA','TBATS','lm','RF','Xgboost','Ensemble','Selected')
# Eval.results_fcastRegion <- data.frame(Eval.results_fcastRegion,Region=rep(Region.groups,each = 4),Results=c('Attainment_Rates','MAPE','MAPE_median','Weighted_MAPE'))
# Eval.results_fcastRegion[,1:9] <- lapply(Eval.results_fcastRegion[,1:9], function(x) as.numeric(as.character(x)))
# 
# Eval.results_wk <- data.frame(Eval.results[,seq(1,18,2)])
# dimnames(Eval.results_wk)[[2]] <- c('MRP','Prophet','ARIMA','TBATS','lm','RF','Xgboost','Ensemble','Selected')
# Eval.results_wk <- data.frame(Eval.results_wk,Region=rep(Region.groups,each = 4),Results=c('Attainment_Rates','MAPE','MAPE_median','Weighted_MAPE'))
# Eval.results_wk[,1:9] <- lapply(Eval.results_wk[,1:9], function(x) as.numeric(as.character(x)))
# 
# write_feather(Eval.results_fcastRegion,"~/Yao_Rdata/Eval.results_fcastRegion.feather")
# write_feather(Eval.results_wk,"~/Yao_Rdata/Eval.results_wk.feather")
```

```{r APE Table}
APE.selected <- results[,c(1,2,seq(4,20,2))]
colnames(APE.selected) <- c("CFG","Region",'MRP','Prophet','ARIMA','TBATS','lm','RF','Xgboost','Ensemble','Selected')

APE.selected %>% datatable(options=list(rowCallback = JS(
  'function(row, data) {
        var num_data = data.slice(1,data.length)
        num_data.sort(function (a, b) {  return a - b;  });
        for(i=1;i < data.length; i++) {
          if(data[i]==num_data[8]) {
          $("td:eq("+i+")", row).css("background-color", "#ffffff")
  } else if(data[i]==num_data[7]) {
        $("td:eq("+i+")", row).css("background-color", "#e6ffe6")
  } else if(data[i]==num_data[6]) {
        $("td:eq("+i+")", row).css("background-color", "#b3ffb3")
  } else if(data[i]==num_data[5]) {
        $("td:eq("+i+")", row).css("background-color", "#80ff80")
  } else if(data[i]==num_data[4]) {
        $("td:eq("+i+")", row).css("background-color", "#4dff4d")
  } else if(data[i]==num_data[3]) {
        $("td:eq("+i+")", row).css("background-color", "#1aff1a")
  } else if(data[i]==num_data[2]) {
        $("td:eq("+i+")", row).css("background-color", "#00e600")
  }
        }
  }'))) %>% 
  formatRound(columns=c('MRP','Prophet','ARIMA','TBATS','lm','RF','Xgboost','Ensemble','Selected'), digits=2) 
```


```{r Visualize Errors}
# ggplotly(filter(Eval.results_fcastRegion,Region==Region.groups[1],Results=='Weighted_MAPE') %>% 
#            select(-Region,-Results,-Selected) %>%
#            gather(key="Model",value="Value") %>%
#            ggplot(aes(Model,Value)) +
#            geom_bar(stat = "identity") +
#            labs(title = paste('Model Comparison by Forecast Region Accuracy'), x = "Models", y = paste(str_replace_all('Weighted_MAPE','_',' '),"(%)")) + 
#            theme_minimal(base_size = 14) + 
#            scale_fill_tableau('tableau10medium'))
# 
# ggplotly(filter(Eval.results_wk,Region==Region.groups[1],Results=='Weighted_MAPE') %>% 
#            select(-Region,-Results,-Selected) %>%
#            gather(key="Model",value="Value") %>%
#            ggplot(aes(Model,Value)) +
#            geom_bar(stat = "identity") +
#            labs(title = paste('Model Comparison by Weekly Accuracy'), x = "Models", y = paste(str_replace_all('Weighted_MAPE','_',' '),"(%)")) + 
#            theme_minimal(base_size = 14) + 
#            scale_fill_tableau('tableau10medium'))

```

```{r close the cluster}
# for Parallel package
stopImplicitCluster()
```

```{r Best Selection for the test region}
# APE.selected <- results[,c(1,2,seq(4,20,2))]
# colnames(APE.selected) <- c("CFG","Region",'MRP','Prophet','ARIMA','TBATS','lm','RF','Xgboost','Ensemble','Selected')
# APE.selected$Selection <- apply(APE.selected,1,function(x) names(which.min(x[4:10])))
# APE.selected[c("Selection" )] <- lapply(APE.selected[c("Selection" )], function(x) as.factor(as.character(x)))
# write_feather(APE.selected,"~/Yao_Rdata/TestSelection.feather")
# APE.selected <- read_feather("~/Yao_Rdata/TestSelection.feather")
```

