---
title: "HDD Forecast Cross-Validation Results Evaluation by Region"
author: "Yao"
date: "June 29, 2018"
output: html_document
---

Updated on 7/17/2018: Add "Ensemble" Model and "Weighted MAPE".
Updated on 7/27/2018: Added more models.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE,message=FALSE)
library(tidyverse)
library(ggthemes)
options(scipen = 999)
library(lubridate)
library(tidyquant)
library(plotly)

library(scales) # for percent

# make the code parallel using 'parallel' package
library(iterators)
library(parallel)
library(foreach)
library(doParallel)

# Calculate the number of cores
no_cores <- detectCores() - 1
registerDoParallel(no_cores)

# fast data format
library(feather)
```

## My models compared to MRP

```{r Load feather data}
# Load feather data
All_fcast <- read_feather("~/Yao_Rdata/All_fcast_CV.feather")
```

Visualization is done in Shiny App.
```{r Visualize all CFGs}
# Get all CFG names, all Region names, and all Model names
CFGgroups <- levels(factor(All_fcast$CFG))
len_CFG <- length(CFGgroups)
Region.groups <- levels(factor(All_fcast$Region))
len_Region <- length(Region.groups)
Quarter.groups <- levels(factor(All_fcast$Quarter))
len_Qtr <- length(Quarter.groups)

l_ggplotly <- htmltools::tagList()
if (1){
  num <- 1
  # For each CFG
  for (i_CFG in 1:len_CFG) {
    # For each Region
    for (i_Region in 1:len_Region){
      # For each Quarter
      for (i_Qtr in 1:len_Qtr){
        p <- ggplot(filter(All_fcast,CFG==CFGgroups[i_CFG],Region==Region.groups[i_Region],Quarter==Quarter.groups[i_Qtr]), aes(x=Fiscal_Wk,y=HDD_QTY,group = Model, color = Model)) +
          geom_point(size = 2) +
          geom_line(size = 1.5,alpha=0.6) +
          labs(title = Quarter.groups[i_Qtr], x = "Fiscal Week", y = "Part Quantity") +
          theme_minimal(base_size = 14) +
          scale_color_tableau('tableau20') +
          scale_x_discrete(breaks = c('W01', 'W07','W13')) +
          scale_y_continuous(label=comma) + expand_limits(y = 0)
        l_ggplotly[[num]] <- ggplotly(p,width = 999)
        num <- num + 1
      }
    }
  }
}
l_ggplotly
```


```{r Calculate errors}
# Data transformation for error calculations
All_fcast[!is.na(All_fcast$Model),] %>% spread(Model,HDD_QTY) %>% ungroup() -> CFG_fcast

# CFG_fcast$Ensemble <- rowMeans(select(CFG_fcast,ARIMA,Prophet,TBATS,_RF,_Xgboost), na.rm = TRUE) # removed _lm
# Will dertermine the Ensemble after evaluating all models.

# CFG_fcast.na.omitted <- na.omit(CFG_fcast) %>% # Excluded some CFGs that do not have all model results. I do not want this.
CFG_fcast <- CFG_fcast %>%
         # calculate abs(error) here
  mutate(err_Prophet = abs(HDD_QTY - Prophet),
         err_ARIMA = abs(HDD_QTY - ARIMA),
         err_TBATS = abs(HDD_QTY - TBATS),
         err_lm = abs(HDD_QTY - lm),
         err_RF = abs(HDD_QTY - RF),
         err_Xgboost = abs(HDD_QTY - Xgboost),
         err_ets = abs(HDD_QTY - ets),
         err_nn = abs(HDD_QTY - nn),
         err_rw = abs(HDD_QTY - rw),
         err_rwd = abs(HDD_QTY - rwd),
         err_stlar = abs(HDD_QTY - stlar),
         err_wn = abs(HDD_QTY - wn),
         err_naive = abs(HDD_QTY - naive),
         # calculate absolute percent error
         ape_Prophet = abs((HDD_QTY - Prophet)/HDD_QTY * 100),
         ape_ARIMA = abs((HDD_QTY - ARIMA)/HDD_QTY * 100),
         ape_TBATS = abs((HDD_QTY - TBATS)/HDD_QTY * 100),
         ape_lm = abs((HDD_QTY - lm)/HDD_QTY * 100),
         ape_RF = abs((HDD_QTY - RF)/HDD_QTY * 100),
         ape_Xgboost = abs((HDD_QTY - Xgboost)/HDD_QTY * 100),
         ape_ets = abs((HDD_QTY - ets)/HDD_QTY * 100),
         ape_nn = abs((HDD_QTY - nn)/HDD_QTY * 100),
         ape_rw = abs((HDD_QTY - rw)/HDD_QTY * 100),
         ape_rwd = abs((HDD_QTY - rwd)/HDD_QTY * 100),
         ape_stlar = abs((HDD_QTY - stlar)/HDD_QTY * 100),
         ape_wn = abs((HDD_QTY - wn)/HDD_QTY * 100),
         ape_naive = abs((HDD_QTY - naive)/HDD_QTY * 100)) #%>%
  
  # # calculate absolute percent error for Ensemble
  # mutate(ape_Ensemble = abs((HDD_QTY - Ensemble)/HDD_QTY * 100))

# Function that returns Root Mean Squared Error
RMSE <- function(error){
    sqrt(mean(error^2,na.rm = TRUE))
}

# Get all CFG names, all Region names, and all Model names
CFGgroups2 <- levels(factor(CFG_fcast$CFG))
len_CFG <- length(CFGgroups2)
Region.groups <- levels(factor(CFG_fcast$Region))
len_Region <- length(Region.groups)
Quarter.groups <- levels(factor(CFG_fcast$Quarter))
len_Quarter <- length(Quarter.groups)

results <- foreach(i_CFG=1:len_CFG, .combine=rbind, .packages=c('tidyverse')) %dopar% {
  # HDD Weekly Sales for certain CFG and selected Region
  # For each Region
  OneCFG <- list()
  for (i_Region in 1:len_Region){
    for (i_Quarter in 1:len_Quarter){
      temp_data <- filter(CFG_fcast,CFG==CFGgroups2[i_CFG],Region==Region.groups[i_Region],Quarter==Quarter.groups[i_Quarter])
      print(paste(CFGgroups2[i_CFG],Region.groups[i_Region],Quarter.groups[i_Quarter],'PASSED!'))
      totalHDD <- sum(temp_data$HDD_QTY)
      w <- temp_data$HDD_QTY/totalHDD
      
      # Prophet
      # Metric 1: Weighted MAPE by Week / WAPE
      mape_wk_Prophet <- weighted.mean(temp_data$ape_Prophet,temp_data$HDD_QTY, na.rm = TRUE)
      # Metric 1.2: WAPE # Is this the same as my Weighted MAPE by Week? Yep!
      WAPE_Prophet <- sum(temp_data$err_Prophet, na.rm = TRUE)/totalHDD*100
      # Metric 1.3: Aggregated APE during the forecast period # The same as 1 and 1.2? No, this cancelled out some errors, which is not good.
      APE_fcastPeriod_Prophet <- abs(sum(temp_data$Prophet, na.rm = TRUE)-totalHDD)/totalHDD * 100
      
      # Metric 2: Aggregated Weighted APE
      Aggregated_weighted_APE_Prophet <- sum(w*temp_data$err_Prophet, na.rm = TRUE)/sum(w*temp_data$HDD_QTY, na.rm = TRUE)*100
      # Metric 3: MASE: Mean Absolute Scaled Error
      MASE_wk_Prophet <- mean(abs(temp_data$err_Prophet/temp_data$err_naive), na.rm = TRUE)
      # Metric 4 Aggregated Absolute Scaled Error
      AASE_fcastPeriod_Prophet <- abs(sum(temp_data$err_Prophet, na.rm = TRUE)/sum(temp_data$err_naive, na.rm = TRUE))
      # Metric 5: Mean RMSE by Week
      RMSE_wk_Prophet <- RMSE(temp_data$err_Prophet)
      # Metric 6: Aggregatred RMSE/MAE per week
      AAE_fcastPeriod_per_week_Prophet <- abs(sum(temp_data$Prophet, na.rm = TRUE)-totalHDD)/nrow(temp_data)
      # Metric 6.2: MAE # The same as 6? No, the Metric 6 cancelled out some errors in different weeks.
      MAE_wk_Prophet <- mean(temp_data$err_Prophet, na.rm = TRUE)
      
      Prophet <- c(CFGgroups2[i_CFG],Region.groups[i_Region],Quarter.groups[i_Quarter],'Prophet',mape_wk_Prophet,WAPE_Prophet,APE_fcastPeriod_Prophet,Aggregated_weighted_APE_Prophet,MASE_wk_Prophet,AASE_fcastPeriod_Prophet,RMSE_wk_Prophet,AAE_fcastPeriod_per_week_Prophet,MAE_wk_Prophet)
      
      # ARIMA
      if (all(is.na(temp_data$ARIMA))) {
        ARIMA <- c(CFGgroups2[i_CFG],Region.groups[i_Region],Quarter.groups[i_Quarter],'ARIMA',rep(NA,9))
      } else{
        # Weekly Error Calculation
        # Metric 1: Weighted MAPE by Week / WAPE
        mape_wk_ARIMA <- weighted.mean(temp_data$ape_ARIMA,temp_data$HDD_QTY, na.rm = TRUE)
        # Metric 1.2: WAPE # Is this the same as my Weighted MAPE by Week? Yep!
        WAPE_ARIMA <- sum(temp_data$err_ARIMA, na.rm = TRUE)/totalHDD*100
        # Metric 1.3: Aggregated APE during the forecast period # The same as 1 and 1.2? Yes!
        APE_fcastPeriod_ARIMA <- abs(sum(temp_data$ARIMA, na.rm = TRUE)-totalHDD)/totalHDD * 100
        
        # Metric 2: Aggregated Weighted APE
        Aggregated_weighted_APE_ARIMA <- sum(w*temp_data$err_ARIMA, na.rm = TRUE)/sum(w*temp_data$HDD_QTY, na.rm = TRUE)*100
        # Metric 3: MASE: Mean Absolute Scaled Error
        MASE_wk_ARIMA <- mean(abs(temp_data$err_ARIMA/temp_data$err_naive), na.rm = TRUE)
        # Metric 4 Aggregated Absolute Scaled Error
        AASE_fcastPeriod_ARIMA <- abs(sum(temp_data$err_ARIMA, na.rm = TRUE)/sum(temp_data$err_naive, na.rm = TRUE))
        # Metric 5: Mean RMSE by Week
        RMSE_wk_ARIMA <- RMSE(temp_data$err_ARIMA)
        # Metric 6: Aggregatred RMSE/MAE per week
        AAE_fcastPeriod_per_week_ARIMA <- abs(sum(temp_data$ARIMA, na.rm = TRUE)-totalHDD)/nrow(temp_data)
        # Metric 6.2: MAE # The same as 6
        MAE_wk_ARIMA <- mean(temp_data$err_ARIMA, na.rm = TRUE)
        
        ARIMA <- c(CFGgroups2[i_CFG],Region.groups[i_Region],Quarter.groups[i_Quarter],'ARIMA',mape_wk_ARIMA,WAPE_ARIMA,APE_fcastPeriod_ARIMA,Aggregated_weighted_APE_ARIMA,MASE_wk_ARIMA,AASE_fcastPeriod_ARIMA,RMSE_wk_ARIMA,AAE_fcastPeriod_per_week_ARIMA,MAE_wk_ARIMA)
      }
      
      # TBATS
      # Metric 1: Weighted MAPE by Week / WAPE
      mape_wk_TBATS <- weighted.mean(temp_data$ape_TBATS,temp_data$HDD_QTY, na.rm = TRUE)
      # Metric 1.2: WAPE # Is this the same as my Weighted MAPE by Week? Yep!
      WAPE_TBATS <- sum(temp_data$err_TBATS, na.rm = TRUE)/totalHDD*100
      # Metric 1.3: Aggregated APE during the forecast period # The same as 1 and 1.2? Yes!
      APE_fcastPeriod_TBATS <- abs(sum(temp_data$TBATS, na.rm = TRUE)-totalHDD)/totalHDD * 100
      
      # Metric 2: Aggregated Weighted APE
      Aggregated_weighted_APE_TBATS <- sum(w*temp_data$err_TBATS, na.rm = TRUE)/sum(w*temp_data$HDD_QTY, na.rm = TRUE)*100
      # Metric 3: MASE: Mean Absolute Scaled Error
      MASE_wk_TBATS <- mean(abs(temp_data$err_TBATS/temp_data$err_naive), na.rm = TRUE)
      # Metric 4 Aggregated Absolute Scaled Error
      AASE_fcastPeriod_TBATS <- abs(sum(temp_data$err_TBATS, na.rm = TRUE)/sum(temp_data$err_naive, na.rm = TRUE))
      # Metric 5: Mean RMSE by Week
      RMSE_wk_TBATS <- RMSE(temp_data$err_TBATS)
      # Metric 6: Aggregatred RMSE/MAE per week
      AAE_fcastPeriod_per_week_TBATS <- abs(sum(temp_data$TBATS, na.rm = TRUE)-totalHDD)/nrow(temp_data)
      # Metric 6.2: MAE # The same as 6
      MAE_wk_TBATS <- mean(temp_data$err_TBATS, na.rm = TRUE)
      
      TBATS <- c(CFGgroups2[i_CFG],Region.groups[i_Region],Quarter.groups[i_Quarter],'TBATS',mape_wk_TBATS,WAPE_TBATS,APE_fcastPeriod_TBATS,Aggregated_weighted_APE_TBATS,MASE_wk_TBATS,AASE_fcastPeriod_TBATS,RMSE_wk_TBATS,AAE_fcastPeriod_per_week_TBATS,MAE_wk_TBATS)
      
      #  lm
      # Metric 1: Weighted MAPE by Week / WAPE
      mape_wk_lm <- weighted.mean(temp_data$ape_lm,temp_data$HDD_QTY, na.rm = TRUE)
      # Metric 1.2: WAPE # Is this the same as my Weighted MAPE by Week? Yep!
      WAPE_lm <- sum(temp_data$err_lm, na.rm = TRUE)/totalHDD*100
      # Metric 1.3: Aggregated APE during the forecast period # The same as 1 and 1.2? Yes!
      APE_fcastPeriod_lm <- abs(sum(temp_data$lm, na.rm = TRUE)-totalHDD)/totalHDD * 100
      
      # Metric 2: Aggregated Weighted APE
      Aggregated_weighted_APE_lm <- sum(w*temp_data$err_lm, na.rm = TRUE)/sum(w*temp_data$HDD_QTY, na.rm = TRUE)*100
      # Metric 3: MASE: Mean Absolute Scaled Error
      MASE_wk_lm <- mean(abs(temp_data$err_lm/temp_data$err_naive), na.rm = TRUE)
      # Metric 4 Aggregated Absolute Scaled Error
      AASE_fcastPeriod_lm <- abs(sum(temp_data$err_lm, na.rm = TRUE)/sum(temp_data$err_naive, na.rm = TRUE))
      # Metric 5: Mean RMSE by Week
      RMSE_wk_lm <- RMSE(temp_data$err_lm)
      # Metric 6: Aggregatred RMSE/MAE per week
      AAE_fcastPeriod_per_week_lm <- abs(sum(temp_data$lm, na.rm = TRUE)-totalHDD)/nrow(temp_data)
      # Metric 6.2: MAE # The same as 6
      MAE_wk_lm <- mean(temp_data$err_lm, na.rm = TRUE)
      
      lm <- c(CFGgroups2[i_CFG],Region.groups[i_Region],Quarter.groups[i_Quarter],'LinearModel',mape_wk_lm,WAPE_lm,APE_fcastPeriod_lm,Aggregated_weighted_APE_lm,MASE_wk_lm,AASE_fcastPeriod_lm,RMSE_wk_lm,AAE_fcastPeriod_per_week_lm,MAE_wk_lm)
      
      #  RF
      # Metric 1: Weighted MAPE by Week / WAPE
      mape_wk_RF <- weighted.mean(temp_data$ape_RF,temp_data$HDD_QTY, na.rm = TRUE)
      # Metric 1.2: WAPE # Is this the same as my Weighted MAPE by Week? Yep!
      WAPE_RF <- sum(temp_data$err_RF, na.rm = TRUE)/totalHDD*100
      # Metric 1.3: Aggregated APE during the forecast period # The same as 1 and 1.2? Yes!
      APE_fcastPeriod_RF <- abs(sum(temp_data$RF, na.rm = TRUE)-totalHDD)/totalHDD * 100
      
      # Metric 2: Aggregated Weighted APE
      Aggregated_weighted_APE_RF <- sum(w*temp_data$err_RF, na.rm = TRUE)/sum(w*temp_data$HDD_QTY, na.rm = TRUE)*100
      # Metric 3: MASE: Mean Absolute Scaled Error
      MASE_wk_RF <- mean(abs(temp_data$err_RF/temp_data$err_naive), na.rm = TRUE)
      # Metric 4 Aggregated Absolute Scaled Error
      AASE_fcastPeriod_RF <- abs(sum(temp_data$err_RF, na.rm = TRUE)/sum(temp_data$err_naive, na.rm = TRUE))
      # Metric 5: Mean RMSE by Week
      RMSE_wk_RF <- RMSE(temp_data$err_RF)
      # Metric 6: Aggregatred RMSE/MAE per week
      AAE_fcastPeriod_per_week_RF <- abs(sum(temp_data$RF, na.rm = TRUE)-totalHDD)/nrow(temp_data)
      # Metric 6.2: MAE # The same as 6
      MAE_wk_RF <- mean(temp_data$err_RF, na.rm = TRUE)
      
      RF <- c(CFGgroups2[i_CFG],Region.groups[i_Region],Quarter.groups[i_Quarter],'RandomForest',mape_wk_RF,WAPE_RF,APE_fcastPeriod_RF,Aggregated_weighted_APE_RF,MASE_wk_RF,AASE_fcastPeriod_RF,RMSE_wk_RF,AAE_fcastPeriod_per_week_RF,MAE_wk_RF)
      
      # Xgboost
      # Metric 1: Weighted MAPE by Week / WAPE
      mape_wk_Xgboost <- weighted.mean(temp_data$ape_Xgboost,temp_data$HDD_QTY, na.rm = TRUE)
      # Metric 1.2: WAPE # Is this the same as my Weighted MAPE by Week? Yep!
      WAPE_Xgboost <- sum(temp_data$err_Xgboost, na.rm = TRUE)/totalHDD*100
      # Metric 1.3: Aggregated APE during the forecast period # The same as 1 and 1.2? Yes!
      APE_fcastPeriod_Xgboost <- abs(sum(temp_data$Xgboost, na.rm = TRUE)-totalHDD)/totalHDD * 100
      
      # Metric 2: Aggregated Weighted APE
      Aggregated_weighted_APE_Xgboost <- sum(w*temp_data$err_Xgboost, na.rm = TRUE)/sum(w*temp_data$HDD_QTY, na.rm = TRUE)*100
      # Metric 3: MASE: Mean Absolute Scaled Error
      MASE_wk_Xgboost <- mean(abs(temp_data$err_Xgboost/temp_data$err_naive), na.rm = TRUE)
      # Metric 4 Aggregated Absolute Scaled Error
      AASE_fcastPeriod_Xgboost <- abs(sum(temp_data$err_Xgboost, na.rm = TRUE)/sum(temp_data$err_naive, na.rm = TRUE))
      # Metric 5: Mean RMSE by Week
      RMSE_wk_Xgboost <- RMSE(temp_data$err_Xgboost)
      # Metric 6: Aggregatred RMSE/MAE per week
      AAE_fcastPeriod_per_week_Xgboost <- abs(sum(temp_data$Xgboost, na.rm = TRUE)-totalHDD)/nrow(temp_data)
      # Metric 6.2: MAE # The same as 6
      MAE_wk_Xgboost <- mean(temp_data$err_Xgboost, na.rm = TRUE)
      
      Xgboost <- c(CFGgroups2[i_CFG],Region.groups[i_Region],Quarter.groups[i_Quarter],'Xgboost',mape_wk_Xgboost,WAPE_Xgboost,APE_fcastPeriod_Xgboost,Aggregated_weighted_APE_Xgboost,MASE_wk_Xgboost,AASE_fcastPeriod_Xgboost,RMSE_wk_Xgboost,AAE_fcastPeriod_per_week_Xgboost,MAE_wk_Xgboost)
      
      # ets
      # Metric 1: Weighted MAPE by Week / WAPE
      mape_wk_ets <- weighted.mean(temp_data$ape_ets,temp_data$HDD_QTY, na.rm = TRUE)
      # Metric 1.2: WAPE # Is this the same as my Weighted MAPE by Week? Yep!
      WAPE_ets <- sum(temp_data$err_ets, na.rm = TRUE)/totalHDD*100
      # Metric 1.3: Aggregated APE during the forecast period # The same as 1 and 1.2? Yes!
      APE_fcastPeriod_ets <- abs(sum(temp_data$ets, na.rm = TRUE)-totalHDD)/totalHDD * 100
      
      # Metric 2: Aggregated Weighted APE
      Aggregated_weighted_APE_ets <- sum(w*temp_data$err_ets, na.rm = TRUE)/sum(w*temp_data$HDD_QTY, na.rm = TRUE)*100
      # Metric 3: MASE: Mean Absolute Scaled Error
      MASE_wk_ets <- mean(abs(temp_data$err_ets/temp_data$err_naive), na.rm = TRUE)
      # Metric 4 Aggregated Absolute Scaled Error
      AASE_fcastPeriod_ets <- abs(sum(temp_data$err_ets, na.rm = TRUE)/sum(temp_data$err_naive, na.rm = TRUE))
      # Metric 5: Mean RMSE by Week
      RMSE_wk_ets <- RMSE(temp_data$err_ets)
      # Metric 6: Aggregatred RMSE/MAE per week
      AAE_fcastPeriod_per_week_ets <- abs(sum(temp_data$ets, na.rm = TRUE)-totalHDD)/nrow(temp_data)
      # Metric 6.2: MAE # The same as 6
      MAE_wk_ets <- mean(temp_data$err_ets, na.rm = TRUE)
      
      ets <- c(CFGgroups2[i_CFG],Region.groups[i_Region],Quarter.groups[i_Quarter],'ets',mape_wk_ets,WAPE_ets,APE_fcastPeriod_ets,Aggregated_weighted_APE_ets,MASE_wk_ets,AASE_fcastPeriod_ets,RMSE_wk_ets,AAE_fcastPeriod_per_week_ets,MAE_wk_ets)
      
      # nn
      # Metric 1: Weighted MAPE by Week / WAPE
      mape_wk_nn <- weighted.mean(temp_data$ape_nn,temp_data$HDD_QTY, na.rm = TRUE)
      # Metric 1.2: WAPE # Is this the same as my Weighted MAPE by Week? Yep!
      WAPE_nn <- sum(temp_data$err_nn, na.rm = TRUE)/totalHDD*100
      # Metric 1.3: Aggregated APE during the forecast period # The same as 1 and 1.2? Yes!
      APE_fcastPeriod_nn <- abs(sum(temp_data$nn, na.rm = TRUE)-totalHDD)/totalHDD * 100
      
      # Metric 2: Aggregated Weighted APE
      Aggregated_weighted_APE_nn <- sum(w*temp_data$err_nn, na.rm = TRUE)/sum(w*temp_data$HDD_QTY, na.rm = TRUE)*100
      # Metric 3: MASE: Mean Absolute Scaled Error
      MASE_wk_nn <- mean(abs(temp_data$err_nn/temp_data$err_naive), na.rm = TRUE)
      # Metric 4 Aggregated Absolute Scaled Error
      AASE_fcastPeriod_nn <- abs(sum(temp_data$err_nn, na.rm = TRUE)/sum(temp_data$err_naive, na.rm = TRUE))
      # Metric 5: Mean RMSE by Week
      RMSE_wk_nn <- RMSE(temp_data$err_nn)
      # Metric 6: Aggregatred RMSE/MAE per week
      AAE_fcastPeriod_per_week_nn <- abs(sum(temp_data$nn, na.rm = TRUE)-totalHDD)/nrow(temp_data)
      # Metric 6.2: MAE # The same as 6
      MAE_wk_nn <- mean(temp_data$err_nn, na.rm = TRUE)
      
      nn <- c(CFGgroups2[i_CFG],Region.groups[i_Region],Quarter.groups[i_Quarter],'nn',mape_wk_nn,WAPE_nn,APE_fcastPeriod_nn,Aggregated_weighted_APE_nn,MASE_wk_nn,AASE_fcastPeriod_nn,RMSE_wk_nn,AAE_fcastPeriod_per_week_nn,MAE_wk_nn)
      
      # rw
      # Metric 1: Weighted MAPE by Week / WAPE
      mape_wk_rw <- weighted.mean(temp_data$ape_rw,temp_data$HDD_QTY, na.rm = TRUE)
      # Metric 1.2: WAPE # Is this the same as my Weighted MAPE by Week? Yep!
      WAPE_rw <- sum(temp_data$err_rw, na.rm = TRUE)/totalHDD*100
      # Metric 1.3: Aggregated APE during the forecast period # The same as 1 and 1.2? Yes!
      APE_fcastPeriod_rw <- abs(sum(temp_data$rw, na.rm = TRUE)-totalHDD)/totalHDD * 100
      
      # Metric 2: Aggregated Weighted APE
      Aggregated_weighted_APE_rw <- sum(w*temp_data$err_rw, na.rm = TRUE)/sum(w*temp_data$HDD_QTY, na.rm = TRUE)*100
      # Metric 3: MASE: Mean Absolute Scaled Error
      MASE_wk_rw <- mean(abs(temp_data$err_rw/temp_data$err_naive), na.rm = TRUE)
      # Metric 4 Aggregated Absolute Scaled Error
      AASE_fcastPeriod_rw <- abs(sum(temp_data$err_rw, na.rm = TRUE)/sum(temp_data$err_naive, na.rm = TRUE))
      # Metric 5: Mean RMSE by Week
      RMSE_wk_rw <- RMSE(temp_data$err_rw)
      # Metric 6: Aggregatred RMSE/MAE per week
      AAE_fcastPeriod_per_week_rw <- abs(sum(temp_data$rw, na.rm = TRUE)-totalHDD)/nrow(temp_data)
      # Metric 6.2: MAE # The same as 6
      MAE_wk_rw <- mean(temp_data$err_rw, na.rm = TRUE)
      
      rw <- c(CFGgroups2[i_CFG],Region.groups[i_Region],Quarter.groups[i_Quarter],'rw',mape_wk_rw,WAPE_rw,APE_fcastPeriod_rw,Aggregated_weighted_APE_rw,MASE_wk_rw,AASE_fcastPeriod_rw,RMSE_wk_rw,AAE_fcastPeriod_per_week_rw,MAE_wk_rw)
      
      # rwd
      # Metric 1: Weighted MAPE by Week / WAPE
      mape_wk_rwd <- weighted.mean(temp_data$ape_rwd,temp_data$HDD_QTY, na.rm = TRUE)
      # Metric 1.2: WAPE # Is this the same as my Weighted MAPE by Week? Yep!
      WAPE_rwd <- sum(temp_data$err_rwd, na.rm = TRUE)/totalHDD*100
      # Metric 1.3: Aggregated APE during the forecast period # The same as 1 and 1.2? Yes!
      APE_fcastPeriod_rwd <- abs(sum(temp_data$rwd, na.rm = TRUE)-totalHDD)/totalHDD * 100
      
      # Metric 2: Aggregated Weighted APE
      Aggregated_weighted_APE_rwd <- sum(w*temp_data$err_rwd, na.rm = TRUE)/sum(w*temp_data$HDD_QTY, na.rm = TRUE)*100
      # Metric 3: MASE: Mean Absolute Scaled Error
      MASE_wk_rwd <- mean(abs(temp_data$err_rwd/temp_data$err_naive), na.rm = TRUE)
      # Metric 4 Aggregated Absolute Scaled Error
      AASE_fcastPeriod_rwd <- abs(sum(temp_data$err_rwd, na.rm = TRUE)/sum(temp_data$err_naive, na.rm = TRUE))
      # Metric 5: Mean RMSE by Week
      RMSE_wk_rwd <- RMSE(temp_data$err_rwd)
      # Metric 6: Aggregatred RMSE/MAE per week
      AAE_fcastPeriod_per_week_rwd <- abs(sum(temp_data$rwd, na.rm = TRUE)-totalHDD)/nrow(temp_data)
      # Metric 6.2: MAE # The same as 6
      MAE_wk_rwd <- mean(temp_data$err_rwd, na.rm = TRUE)
      
      rwd <- c(CFGgroups2[i_CFG],Region.groups[i_Region],Quarter.groups[i_Quarter],'rwd',mape_wk_rwd,WAPE_rwd,APE_fcastPeriod_rwd,Aggregated_weighted_APE_rwd,MASE_wk_rwd,AASE_fcastPeriod_rwd,RMSE_wk_rwd,AAE_fcastPeriod_per_week_rwd,MAE_wk_rwd)
      
      # stlar
      # Metric 1: Weighted MAPE by Week / WAPE
      mape_wk_stlar <- weighted.mean(temp_data$ape_stlar,temp_data$HDD_QTY, na.rm = TRUE)
      # Metric 1.2: WAPE # Is this the same as my Weighted MAPE by Week? Yep!
      WAPE_stlar <- sum(temp_data$err_stlar, na.rm = TRUE)/totalHDD*100
      # Metric 1.3: Aggregated APE during the forecast period # The same as 1 and 1.2? Yes!
      APE_fcastPeriod_stlar <- abs(sum(temp_data$stlar, na.rm = TRUE)-totalHDD)/totalHDD * 100
      
      # Metric 2: Aggregated Weighted APE
      Aggregated_weighted_APE_stlar <- sum(w*temp_data$err_stlar, na.rm = TRUE)/sum(w*temp_data$HDD_QTY, na.rm = TRUE)*100
      # Metric 3: MASE: Mean Absolute Scaled Error
      MASE_wk_stlar <- mean(abs(temp_data$err_stlar/temp_data$err_naive), na.rm = TRUE)
      # Metric 4 Aggregated Absolute Scaled Error
      AASE_fcastPeriod_stlar <- abs(sum(temp_data$err_stlar, na.rm = TRUE)/sum(temp_data$err_naive, na.rm = TRUE))
      # Metric 5: Mean RMSE by Week
      RMSE_wk_stlar <- RMSE(temp_data$err_stlar)
      # Metric 6: Aggregatred RMSE/MAE per week
      AAE_fcastPeriod_per_week_stlar <- abs(sum(temp_data$stlar, na.rm = TRUE)-totalHDD)/nrow(temp_data)
      # Metric 6.2: MAE # The same as 6
      MAE_wk_stlar <- mean(temp_data$err_stlar, na.rm = TRUE)
      
      stlar <- c(CFGgroups2[i_CFG],Region.groups[i_Region],Quarter.groups[i_Quarter],'stlar',mape_wk_stlar,WAPE_stlar,APE_fcastPeriod_stlar,Aggregated_weighted_APE_stlar,MASE_wk_stlar,AASE_fcastPeriod_stlar,RMSE_wk_stlar,AAE_fcastPeriod_per_week_stlar,MAE_wk_stlar)
      
      # wn
      # Metric 1: Weighted MAPE by Week / WAPE
      mape_wk_wn <- weighted.mean(temp_data$ape_wn,temp_data$HDD_QTY, na.rm = TRUE)
      # Metric 1.2: WAPE # Is this the same as my Weighted MAPE by Week? Yep!
      WAPE_wn <- sum(temp_data$err_wn, na.rm = TRUE)/totalHDD*100
      # Metric 1.3: Aggregated APE during the forecast period # The same as 1 and 1.2? Yes!
      APE_fcastPeriod_wn <- abs(sum(temp_data$wn, na.rm = TRUE)-totalHDD)/totalHDD * 100
      
      # Metric 2: Aggregated Weighted APE
      Aggregated_weighted_APE_wn <- sum(w*temp_data$err_wn, na.rm = TRUE)/sum(w*temp_data$HDD_QTY, na.rm = TRUE)*100
      # Metric 3: MASE: Mean Absolute Scaled Error
      MASE_wk_wn <- mean(abs(temp_data$err_wn/temp_data$err_naive), na.rm = TRUE)
      # Metric 4 Aggregated Absolute Scaled Error
      AASE_fcastPeriod_wn <- abs(sum(temp_data$err_wn, na.rm = TRUE)/sum(temp_data$err_naive, na.rm = TRUE))
      # Metric 5: Mean RMSE by Week
      RMSE_wk_wn <- RMSE(temp_data$err_wn)
      # Metric 6: Aggregatred RMSE/MAE per week
      AAE_fcastPeriod_per_week_wn <- abs(sum(temp_data$wn, na.rm = TRUE)-totalHDD)/nrow(temp_data)
      # Metric 6.2: MAE # The same as 6
      MAE_wk_wn <- mean(temp_data$err_wn, na.rm = TRUE)
      
      wn <- c(CFGgroups2[i_CFG],Region.groups[i_Region],Quarter.groups[i_Quarter],'wn',mape_wk_wn,WAPE_wn,APE_fcastPeriod_wn,Aggregated_weighted_APE_wn,MASE_wk_wn,AASE_fcastPeriod_wn,RMSE_wk_wn,AAE_fcastPeriod_per_week_wn,MAE_wk_wn)
            
      # naive
      # Metric 1: Weighted MAPE by Week / WAPE
      mape_wk_naive <- weighted.mean(temp_data$ape_naive,temp_data$HDD_QTY, na.rm = TRUE)
      # Metric 1.2: WAPE # Is this the same as my Weighted MAPE by Week? Yep!
      WAPE_naive <- sum(temp_data$err_naive, na.rm = TRUE)/totalHDD*100
      # Metric 1.3: Aggregated APE during the forecast period # The same as 1 and 1.2? Yes!
      APE_fcastPeriod_naive <- abs(sum(temp_data$naive, na.rm = TRUE)-totalHDD)/totalHDD * 100
      
      # Metric 2: Aggregated Weighted APE
      Aggregated_weighted_APE_naive <- sum(w*temp_data$err_naive, na.rm = TRUE)/sum(w*temp_data$HDD_QTY, na.rm = TRUE)*100
      # Metric 3: MASE: Mean Absolute Scaled Error
      MASE_wk_naive <- mean(abs(temp_data$err_naive/temp_data$err_naive), na.rm = TRUE)
      # Metric 4 Aggregated Absolute Scaled Error
      AASE_fcastPeriod_naive <- abs(sum(temp_data$err_naive, na.rm = TRUE)/sum(temp_data$err_naive, na.rm = TRUE))
      # Metric 5: Mean RMSE by Week
      RMSE_wk_naive <- RMSE(temp_data$err_naive)
      # Metric 6: Aggregatred RMSE/MAE per week
      AAE_fcastPeriod_per_week_naive <- abs(sum(temp_data$naive, na.rm = TRUE)-totalHDD)/nrow(temp_data)
      # Metric 6.2: MAE # The same as 6
      MAE_wk_naive <- mean(temp_data$err_naive, na.rm = TRUE)
      
      naive <- c(CFGgroups2[i_CFG],Region.groups[i_Region],Quarter.groups[i_Quarter],'naive',mape_wk_naive,WAPE_naive,APE_fcastPeriod_naive,Aggregated_weighted_APE_naive,MASE_wk_naive,AASE_fcastPeriod_naive,RMSE_wk_naive,AAE_fcastPeriod_per_week_naive,MAE_wk_naive)
      
      OneRow <- rbind(Prophet,ARIMA,TBATS,lm,RF,Xgboost,ets,nn,rw,rwd,stlar,wn,naive)
      OneCFG <- rbind(OneCFG,OneRow)
    }
  }
  return(OneCFG)
}

dimnames(results)[[2]] <- c('CFG','Region','Quarter','Model','MAPE_wk','WAPE','APE_fcastPeriod','Aggregated_weighted_APE','MASE_wk','AASE_fcastPeriod','RMSE_wk','AAE_fcastPeriod_per_week','MAE_wk')
results <- data.frame(results)
indx <- c('MAPE_wk','WAPE','APE_fcastPeriod','Aggregated_weighted_APE','MASE_wk','AASE_fcastPeriod','RMSE_wk','AAE_fcastPeriod_per_week','MAE_wk')
results[indx] <- lapply(results[indx], function(x) as.numeric(as.character(x)))
results[c("CFG","Region",'Quarter','Model')] <- lapply(results[c("CFG","Region",'Quarter','Model' )], function(x) as.character(x))

#results %>% left_join(CFG_RGN_QTR_data.grouped, by = c("CFG","Region"="RGN_DESC")) -> results.weight

path <- "~/Yao_Rdata/EvaluationResults_CV.feather"
write_feather(results, path)
write_excel_csv(results,'~/Yao_Rdata/Eval_Results_CV.csv')
```

```{r fig.height=100, eval=FALSE, include=FALSE, r fig.height=100}
######
results <- read_feather("~/Yao_Rdata/EvaluationResults_CV.feather")

results %>% gather(key = "Metrics", value = 'Value',MAPE_wk:MAE_wk) %>%
  group_by(Region,Model,Metrics,Quarter) %>% 
  summarise(MeanError=mean(Value, na.rm = TRUE)) -> results4plot

colnames(results4plot)[colnames(results4plot)=="RandomForest"] <- "RF"
# Get all Region names, quater names, and all Metric names
Region.groups <- levels(factor(results4plot$Region))
len_Region <- length(Region.groups)
Quarter.groups <- levels(factor(results4plot$Quarter))
len_Qtr <- length(Quarter.groups)
Metrics.groups <- levels(factor(results4plot$Metrics))
len_Metrics <- length(Metrics.groups)
# Plot one by one then
l_ggplotly <- htmltools::tagList()
if (1){
  num <- 1
  # For each CFG
  for (i_Metrics in 1:len_Metrics) {
    # For each Region
    for (i_Region in 1:len_Region){
      # For each Quarter
      for (i_Qtr in 1:len_Qtr){
        p <- results4plot %>% filter(Metrics==Metrics.groups[i_Metrics],Region==Region.groups[i_Region],Quarter==Quarter.groups[i_Qtr],Model!='LinearModel') %>%
          ggplot(aes(Model,MeanError,fill=Model)) +
          geom_bar(stat = "identity") +
          labs(title = paste(Region.groups[i_Region],Quarter.groups[i_Qtr],Metrics.groups[i_Metrics]), x = "Models", y = 'Metric Value') + 
          theme_minimal(base_size = 14) + 
          scale_fill_tableau('tableau20')
        l_ggplotly[[num]] <- ggplotly(p,width = 999)
        num <- num + 1
      }
    }
  }
}
l_ggplotly
```

```{r Attainment Rates, eval=FALSE, include=FALSE}
# Overall evaluatiion for all CFGs
results <- read_feather("~/Yao_Rdata/EvaluationResults_CV.feather")

results %>% filter(Region=='Global') %>%
  gather(key = "Metrics", value = 'Value',MAPE_wk:MAE_wk) %>%
  group_by(CFG,Model,Metrics) %>% 
  summarise(MeanError=mean(Value, na.rm = TRUE)) %>%
  spread(Metrics,MeanError) -> results4AR

# Attainment Rates
Attainment_Rate_Cal <- function(x) {
  length(which(x<=20))/sum(!is.na(x))*100
}

# Forecast Region Calculation
# Consider all CFGs
results4AR %>% group_by(Model) %>% 
  summarize(AttainmentRate_AAPE=Attainment_Rate_Cal(APE_fcastPeriod),
            AttainmentRate_AWAPE=Attainment_Rate_Cal(Aggregated_weighted_APE),
            AttainmentRate_MAPE_wk=Attainment_Rate_Cal(MAPE_wk),
            AttainmentRate_WAPE=Attainment_Rate_Cal(WAPE)) -> AttainmentRate.results

# Viz the errors
colnames(results4AR)[colnames(results4AR)=="RandomForest"] <- "RF"
ggplotly(AttainmentRate.results %>%
           ggplot(aes(Model,AttainmentRate_AAPE)) +
           geom_bar(stat = "identity") +
           labs(title = paste('Forecast Accuracy of Four Quarter Cross-Validation'), x = "Models", y = 'Attainment Rates (%)') + 
           theme_minimal(base_size = 14) + 
           scale_fill_tableau('tableau10medium'))
```


```{r close the cluster}
# for Parallel package
stopImplicitCluster()
```

